import React, { createContext, useContext, useEffect, useMemo } from 'react';
import { LANGUAGES } from './mock';

const DICT = {
  en: {
    'GOVT OF INDIA':'GOVT OF INDIA','National Welfare & Credit Guidance Platform':'National Welfare & Credit Guidance Platform',
    'Helpline: 1800-11-2026 (Toll-Free)':'Helpline: 1800-11-2026 (Toll-Free)','Government Citizen Platform':'Government Citizen Platform',
    'Home':'Home','Explore Schemes':'Explore Schemes','Smart Matching':'Smart Matching','Financial Calculator':'Financial Calculator',
    'Find Nearby Partner':'Find Nearby Partner','More':'More','Citizen Login':'Citizen Login','Register':'Register',
    'Official':'Official','Decrease font size':'Decrease font size','Reset font size':'Reset font size','Increase font size':'Increase font size',
    'All Schemes Directory':'All Schemes Directory','Smart Scheme Matching':'Smart Scheme Matching','Loan & Subsidy Calculator':'Loan & Subsidy Calculator',
    'Nearby Partner Centers':'Nearby Partner Centers','Sign In / Portal':'Sign In / Portal','QUICK LINKS':'QUICK LINKS',
    'SUPPORT & HELPLINE':'SUPPORT & HELPLINE','GOVERNANCE & TRUST':'GOVERNANCE & TRUST','Verified':'Verified','Call':'Call','Directions':'Directions',
    'Use My Location':'Use My Location','No partners found for your search.':'No partners found for your search.',
    'Scheme not found':'Scheme not found','Back to Directory':'Back to Directory','Government Verified':'Government Verified',
    'Eligibility Criteria':'Eligibility Criteria','Required Documents':'Required Documents','Ready to Apply?':'Ready to Apply?',
    'Find Partner':'Find Partner','Apply on Portal':'Apply on Portal','Max Support / Loan':'Max Support / Loan','Interest Rate':'Interest Rate',
    'Application Route':'Application Route','Reset':'Reset','CivicLink Assistant':'CivicLink Assistant','Rule-based scheme guidance':'Rule-based scheme guidance',
    'Analyzing your profile against 90 government schemes...':'Analyzing your profile against 90 government schemes...',
    'Type your answer...':'Type your answer...','Voice input':'Voice input','This page does not exist.':'This page does not exist.',
    'Authentication is optional. You can use CivicLink without an account.':'Authentication is optional. You can use CivicLink without an account.',
    'Mobile number':'Mobile number','Password / OTP':'Password / OTP'
  },
  hi: {
    'GOVT OF INDIA':'भारत सरकार','National Welfare & Credit Guidance Platform':'राष्ट्रीय कल्याण एवं ऋण मार्गदर्शन मंच','Helpline: 1800-11-2026 (Toll-Free)':'हेल्पलाइन: 1800-11-2026 (टोल-फ्री)',
    'Government Citizen Platform':'सरकारी नागरिक मंच','Home':'होम','Explore Schemes':'योजनाएँ देखें','Smart Matching':'स्मार्ट मिलान','Financial Calculator':'वित्तीय कैलकुलेटर','Find Nearby Partner':'नज़दीकी साझेदार खोजें','More':'अधिक','Citizen Login':'नागरिक लॉगिन','Register':'पंजीकरण','Official':'आधिकारिक',
    'All Schemes Directory':'सभी योजनाओं की सूची','Smart Scheme Matching':'स्मार्ट योजना मिलान','Loan & Subsidy Calculator':'ऋण एवं सब्सिडी कैलकुलेटर','Nearby Partner Centers':'नज़दीकी साझेदार केंद्र','Sign In / Portal':'साइन इन / पोर्टल','QUICK LINKS':'त्वरित लिंक','SUPPORT & HELPLINE':'सहायता एवं हेल्पलाइन','GOVERNANCE & TRUST':'शासन एवं विश्वास','Verified':'सत्यापित','Call':'कॉल','Directions':'दिशा-निर्देश','Use My Location':'मेरी लोकेशन इस्तेमाल करें','No partners found for your search.':'आपकी खोज के लिए कोई साझेदार नहीं मिला।','Scheme not found':'योजना नहीं मिली','Back to Directory':'सूची पर वापस जाएँ','Government Verified':'सरकार द्वारा सत्यापित','Eligibility Criteria':'पात्रता मानदंड','Required Documents':'आवश्यक दस्तावेज़','Ready to Apply?':'आवेदन के लिए तैयार?','Find Partner':'साझेदार खोजें','Apply on Portal':'पोर्टल पर आवेदन करें','Max Support / Loan':'अधिकतम सहायता / ऋण','Interest Rate':'ब्याज दर','Application Route':'आवेदन का तरीका','Reset':'रीसेट','CivicLink Assistant':'सिविक लिंक सहायक','Rule-based scheme guidance':'नियम-आधारित योजना मार्गदर्शन','Analyzing your profile against 90 government schemes...':'90 सरकारी योजनाओं के अनुसार आपकी प्रोफ़ाइल का विश्लेषण हो रहा है...','Type your answer...':'अपना उत्तर लिखें...','Voice input':'आवाज़ से इनपुट','This page does not exist.':'यह पेज मौजूद नहीं है।','Authentication is optional. You can use CivicLink without an account.':'प्रमाणीकरण वैकल्पिक है। आप बिना खाते के CivicLink का उपयोग कर सकते हैं।','Mobile number':'मोबाइल नंबर','Password / OTP':'पासवर्ड / OTP'
  },
  bn: {'Home':'হোম','Explore Schemes':'প্রকল্প দেখুন','Smart Matching':'স্মার্ট ম্যাচিং','Financial Calculator':'আর্থিক ক্যালকুলেটর','Find Nearby Partner':'কাছের অংশীদার খুঁজুন','More':'আরও','Citizen Login':'নাগরিক লগইন','Register':'নিবন্ধন','Official':'সরকারি','All Schemes Directory':'সব প্রকল্পের তালিকা','Smart Scheme Matching':'স্মার্ট প্রকল্প ম্যাচিং','Loan & Subsidy Calculator':'ঋণ ও ভর্তুকি ক্যালকুলেটর','Verified':'যাচাইকৃত','Call':'কল','Directions':'দিকনির্দেশ','Use My Location':'আমার অবস্থান ব্যবহার করুন','No partners found for your search.':'আপনার অনুসন্ধানে কোনো অংশীদার পাওয়া যায়নি।','Scheme not found':'প্রকল্প পাওয়া যায়নি','Back to Directory':'তালিকায় ফিরুন','Government Verified':'সরকারি যাচাইকৃত','Eligibility Criteria':'যোগ্যতার মানদণ্ড','Required Documents':'প্রয়োজনীয় নথি','Ready to Apply?':'আবেদন করতে প্রস্তুত?','Find Partner':'অংশীদার খুঁজুন','Apply on Portal':'পোর্টালে আবেদন করুন','Max Support / Loan':'সর্বোচ্চ সহায়তা / ঋণ','Interest Rate':'সুদের হার','Application Route':'আবেদনের পদ্ধতি','Reset':'রিসেট','CivicLink Assistant':'CivicLink সহায়ক','Type your answer...':'আপনার উত্তর লিখুন...','Voice input':'ভয়েস ইনপুট','This page does not exist.':'এই পৃষ্ঠাটি নেই।'},
  ta: {'Home':'முகப்பு','Explore Schemes':'திட்டங்களைப் பார்க்க','Smart Matching':'ஸ்மார்ட் பொருத்தம்','Financial Calculator':'நிதி கணிப்பான்','Find Nearby Partner':'அருகிலுள்ள கூட்டாளரைத் தேடு','More':'மேலும்','Citizen Login':'குடிமக்கள் உள்நுழைவு','Register':'பதிவு','Official':'அதிகாரப்பூர்வ','All Schemes Directory':'அனைத்து திட்டங்கள்','Verified':'சரிபார்க்கப்பட்டது','Call':'அழைப்பு','Directions':'வழிகள்','Use My Location':'என் இருப்பிடத்தைப் பயன்படுத்து','Scheme not found':'திட்டம் கிடைக்கவில்லை','Back to Directory':'பட்டியலுக்குத் திரும்பு','Government Verified':'அரசால் சரிபார்க்கப்பட்டது','Eligibility Criteria':'தகுதி அளவுகோல்கள்','Required Documents':'தேவையான ஆவணங்கள்','Ready to Apply?':'விண்ணப்பிக்கத் தயாரா?','Find Partner':'கூட்டாளரைக் கண்டுபிடி','Apply on Portal':'போர்டலில் விண்ணப்பி','Max Support / Loan':'அதிகபட்ச உதவி / கடன்','Interest Rate':'வட்டி விகிதம்','Application Route':'விண்ணப்ப முறை','Reset':'மீட்டமை','CivicLink Assistant':'CivicLink உதவியாளர்','Type your answer...':'உங்கள் பதிலை உள்ளிடவும்...','Voice input':'குரல் உள்ளீடு','This page does not exist.':'இந்தப் பக்கம் இல்லை.'},
  te: {'Home':'హోమ్','Explore Schemes':'పథకాలను చూడండి','Smart Matching':'స్మార్ట్ మ్యాచ్','Financial Calculator':'ఆర్థిక కాలిక్యులేటర్','Find Nearby Partner':'సమీప భాగస్వామిని కనుగొనండి','More':'మరిన్ని','Citizen Login':'పౌర లాగిన్','Register':'నమోదు','Official':'అధికారిక','All Schemes Directory':'అన్ని పథకాల జాబితా','Verified':'ధృవీకరించబడింది','Call':'కాల్','Directions':'దిశలు','Use My Location':'నా స్థానాన్ని ఉపయోగించండి','Scheme not found':'పథకం కనబడలేదు','Back to Directory':'జాబితాకు తిరిగి వెళ్లండి','Government Verified':'ప్రభుత్వ ధృవీకరణ','Eligibility Criteria':'అర్హత ప్రమాణాలు','Required Documents':'అవసరమైన పత్రాలు','Ready to Apply?':'దరఖాస్తు చేయడానికి సిద్ధంగా ఉన్నారా?','Find Partner':'భాగస్వామిని కనుగొనండి','Apply on Portal':'పోర్టల్‌లో దరఖాస్తు చేయండి','Max Support / Loan':'గరిష్ఠ సహాయం / రుణం','Interest Rate':'వడ్డీ రేటు','Application Route':'దరఖాస్తు విధానం','Reset':'రీసెట్','CivicLink Assistant':'CivicLink సహాయకుడు','Type your answer...':'మీ సమాధానాన్ని టైప్ చేయండి...','Voice input':'వాయిస్ ఇన్‌పుట్','This page does not exist.':'ఈ పేజీ లేదు.'},
  mr: {'Home':'मुख्यपृष्ठ','Explore Schemes':'योजना पहा','Smart Matching':'स्मार्ट जुळणी','Financial Calculator':'आर्थिक कॅल्क्युलेटर','Find Nearby Partner':'जवळचा भागीदार शोधा','More':'अधिक','Citizen Login':'नागरिक लॉगिन','Register':'नोंदणी','Official':'अधिकृत','All Schemes Directory':'सर्व योजनांची यादी','Verified':'सत्यापित','Call':'कॉल','Directions':'दिशा','Use My Location':'माझे स्थान वापरा','Scheme not found':'योजना सापडली नाही','Back to Directory':'यादीकडे परत जा','Government Verified':'सरकारद्वारे सत्यापित','Eligibility Criteria':'पात्रता निकष','Required Documents':'आवश्यक कागदपत्रे','Ready to Apply?':'अर्ज करण्यास तयार आहात?','Find Partner':'भागीदार शोधा','Apply on Portal':'पोर्टलवर अर्ज करा','Max Support / Loan':'कमाल मदत / कर्ज','Interest Rate':'व्याजदर','Application Route':'अर्ज पद्धत','Reset':'रीसेट','CivicLink Assistant':'CivicLink सहाय्यक','Type your answer...':'तुमचे उत्तर टाइप करा...','Voice input':'व्हॉइस इनपुट','This page does not exist.':'हे पृष्ठ अस्तित्वात नाही.'},
  gu: {'Home':'હોમ','Explore Schemes':'યોજનાઓ જુઓ','Smart Matching':'સ્માર્ટ મેચિંગ','Financial Calculator':'નાણાકીય કેલ્ક્યુલેટર','Find Nearby Partner':'નજીકનો ભાગીદાર શોધો','More':'વધુ','Citizen Login':'નાગરિક લૉગિન','Register':'નોંધણી','Official':'સત્તાવાર','All Schemes Directory':'તમામ યોજનાઓની યાદી','Verified':'ચકાસાયેલ','Call':'કૉલ','Directions':'દિશા-નિર્દેશ','Use My Location':'મારું સ્થાન વાપરો','Scheme not found':'યોજના મળી નથી','Back to Directory':'યાદી પર પાછા જાઓ','Government Verified':'સરકાર દ્વારા ચકાસાયેલ','Eligibility Criteria':'પાત્રતા માપદંડ','Required Documents':'જરૂરી દસ્તાવેજો','Ready to Apply?':'અરજી કરવા તૈયાર છો?','Find Partner':'ભાગીદાર શોધો','Apply on Portal':'પોર્ટલ પર અરજી કરો','Max Support / Loan':'મહત્તમ સહાય / લોન','Interest Rate':'વ્યાજ દર','Application Route':'અરજીનો માર્ગ','Reset':'રીસેટ','CivicLink Assistant':'CivicLink સહાયક','Type your answer...':'તમારો જવાબ લખો...','Voice input':'વૉઇસ ઇનપુટ','This page does not exist.':'આ પૃષ્ઠ અસ્તિત્વમાં નથી.'},
  kn: {'Home':'ಮುಖಪುಟ','Explore Schemes':'ಯೋಜನೆಗಳನ್ನು ನೋಡಿ','Smart Matching':'ಸ್ಮಾರ್ಟ್ ಹೊಂದಾಣಿಕೆ','Financial Calculator':'ಹಣಕಾಸು ಕ್ಯಾಲ್ಕುಲೇಟರ್','Find Nearby Partner':'ಹತ್ತಿರದ ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ','More':'ಇನ್ನಷ್ಟು','Citizen Login':'ನಾಗರಿಕ ಲಾಗಿನ್','Register':'ನೋಂದಣಿ','Official':'ಅಧಿಕೃತ','All Schemes Directory':'ಎಲ್ಲಾ ಯೋಜನೆಗಳ ಪಟ್ಟಿ','Verified':'ಪರಿಶೀಲಿಸಲಾಗಿದೆ','Call':'ಕರೆ','Directions':'ದಿಕ್ಕುಗಳು','Use My Location':'ನನ್ನ ಸ್ಥಳ ಬಳಸಿ','Scheme not found':'ಯೋಜನೆ ಕಂಡುಬಂದಿಲ್ಲ','Back to Directory':'ಪಟ್ಟಿಗೆ ಹಿಂತಿರುಗಿ','Government Verified':'ಸರ್ಕಾರದಿಂದ ಪರಿಶೀಲಿಸಲಾಗಿದೆ','Eligibility Criteria':'ಅರ್ಹತಾ ಮಾನದಂಡಗಳು','Required Documents':'ಅಗತ್ಯ ದಾಖಲೆಗಳು','Ready to Apply?':'ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಸಿದ್ಧವೇ?','Find Partner':'ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ','Apply on Portal':'ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ','Max Support / Loan':'ಗರಿಷ್ಠ ಸಹಾಯ / ಸಾಲ','Interest Rate':'ಬಡ್ಡಿ ದರ','Application Route':'ಅರ್ಜಿ ವಿಧಾನ','Reset':'ಮರುಹೊಂದಿಸಿ','CivicLink Assistant':'CivicLink ಸಹಾಯಕ','Type your answer...':'ನಿಮ್ಮ ಉತ್ತರವನ್ನು ಟೈಪ್ ಮಾಡಿ...','Voice input':'ಧ್ವನಿ ಇನ್‌ಪುಟ್','This page does not exist.':'ಈ ಪುಟ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ.'},
  ml: {'Home':'ഹോം','Explore Schemes':'പദ്ധതികൾ കാണുക','Smart Matching':'സ്മാർട്ട് മാച്ചിംഗ്','Financial Calculator':'സാമ്പത്തിക കാൽക്കുലേറ്റർ','Find Nearby Partner':'അടുത്തുള്ള പങ്കാളിയെ കണ്ടെത്തുക','More':'കൂടുതൽ','Citizen Login':'പൗര ലോഗിൻ','Register':'രജിസ്റ്റർ','Official':'ഔദ്യോഗിക','All Schemes Directory':'എല്ലാ പദ്ധതികളുടെയും പട്ടിക','Verified':'പരിശോധിച്ചത്','Call':'വിളിക്കുക','Directions':'ദിശകൾ','Use My Location':'എന്റെ സ്ഥലം ഉപയോഗിക്കുക','Scheme not found':'പദ്ധതി കണ്ടെത്തിയില്ല','Back to Directory':'പട്ടികയിലേക്ക് മടങ്ങുക','Government Verified':'സർക്കാർ പരിശോധിച്ചത്','Eligibility Criteria':'യോഗ്യതാ മാനദണ്ഡങ്ങൾ','Required Documents':'ആവശ്യമായ രേഖകൾ','Ready to Apply?':'അപേക്ഷിക്കാൻ തയ്യാറാണോ?','Find Partner':'പങ്കാളിയെ കണ്ടെത്തുക','Apply on Portal':'പോർട്ടലിൽ അപേക്ഷിക്കുക','Max Support / Loan':'പരമാവധി സഹായം / വായ്പ','Interest Rate':'പലിശ നിരക്ക്','Application Route':'അപേക്ഷാ മാർഗം','Reset':'റീസെറ്റ്','CivicLink Assistant':'CivicLink സഹായി','Type your answer...':'നിങ്ങളുടെ ഉത്തരം ടൈപ്പ് ചെയ്യുക...','Voice input':'വോയ്സ് ഇൻപുട്ട്','This page does not exist.':'ഈ പേജ് നിലവിലില്ല.'},
  pa: {'Home':'ਹੋਮ','Explore Schemes':'ਸਕੀਮਾਂ ਵੇਖੋ','Smart Matching':'ਸਮਾਰਟ ਮੈਚਿੰਗ','Financial Calculator':'ਵਿੱਤੀ ਕੈਲਕੁਲੇਟਰ','Find Nearby Partner':'ਨੇੜਲਾ ਭਾਈਵਾਲ ਲੱਭੋ','More':'ਹੋਰ','Citizen Login':'ਨਾਗਰਿਕ ਲੌਗਇਨ','Register':'ਰਜਿਸਟਰ','Official':'ਅਧਿਕਾਰਤ','All Schemes Directory':'ਸਾਰੀਆਂ ਸਕੀਮਾਂ ਦੀ ਸੂਚੀ','Verified':'ਪ੍ਰਮਾਣਿਤ','Call':'ਕਾਲ','Directions':'ਦਿਸ਼ਾਵਾਂ','Use My Location':'ਮੇਰੀ ਸਥਿਤੀ ਵਰਤੋ','Scheme not found':'ਸਕੀਮ ਨਹੀਂ ਮਿਲੀ','Back to Directory':'ਸੂਚੀ ਤੇ ਵਾਪਸ ਜਾਓ','Government Verified':'ਸਰਕਾਰ ਵੱਲੋਂ ਪ੍ਰਮਾਣਿਤ','Eligibility Criteria':'ਯੋਗਤਾ ਮਾਪਦੰਡ','Required Documents':'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼','Ready to Apply?':'ਅਰਜ਼ੀ ਲਈ ਤਿਆਰ ਹੋ?','Find Partner':'ਭਾਈਵਾਲ ਲੱਭੋ','Apply on Portal':'ਪੋਰਟਲ ਤੇ ਅਰਜ਼ੀ ਦਿਓ','Max Support / Loan':'ਵੱਧ ਤੋਂ ਵੱਧ ਸਹਾਇਤਾ / ਕਰਜ਼ਾ','Interest Rate':'ਵਿਆਜ ਦਰ','Application Route':'ਅਰਜ਼ੀ ਦਾ ਰਸਤਾ','Reset':'ਰੀਸੈੱਟ','CivicLink Assistant':'CivicLink ਸਹਾਇਕ','Type your answer...':'ਆਪਣਾ ਜਵਾਬ ਲਿਖੋ...','Voice input':'ਆਵਾਜ਼ ਇਨਪੁੱਟ','This page does not exist.':'ਇਹ ਪੰਨਾ ਮੌਜੂਦ ਨਹੀਂ ਹੈ.'},
  or: {'Home':'ମୁଖ୍ୟ ପୃଷ୍ଠା','Explore Schemes':'ଯୋଜନା ଦେଖନ୍ତୁ','Smart Matching':'ସ୍ମାର୍ଟ ମ୍ୟାଚିଂ','Financial Calculator':'ଆର୍ଥିକ କ୍ୟାଲକୁଲେଟର','Find Nearby Partner':'ନିକଟସ୍ଥ ସହଭାଗୀ ଖୋଜନ୍ତୁ','More':'ଅଧିକ','Citizen Login':'ନାଗରିକ ଲଗଇନ','Register':'ପଞ୍ଜୀକରଣ','Official':'ସରକାରୀ','All Schemes Directory':'ସମସ୍ତ ଯୋଜନା ତାଲିକା','Verified':'ଯାଞ୍ଚିତ','Call':'କଲ୍','Directions':'ଦିଗନିର୍ଦ୍ଦେଶ','Use My Location':'ମୋ ଅବସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ','Scheme not found':'ଯୋଜନା ମିଳିଲା ନାହିଁ','Back to Directory':'ତାଲିକାକୁ ଫେରନ୍ତୁ','Government Verified':'ସରକାରୀ ଯାଞ୍ଚିତ','Eligibility Criteria':'ଯୋଗ୍ୟତା ମାନଦଣ୍ଡ','Required Documents':'ଆବଶ୍ୟକ ଦଲିଲ','Ready to Apply?':'ଆବେଦନ ପାଇଁ ପ୍ରସ୍ତୁତ?','Find Partner':'ସହଭାଗୀ ଖୋଜନ୍ତୁ','Apply on Portal':'ପୋର୍ଟାଲରେ ଆବେଦନ କରନ୍ତୁ','Max Support / Loan':'ସର୍ବାଧିକ ସହାୟତା / ଋଣ','Interest Rate':'ସୁଧ ହାର','Application Route':'ଆବେଦନ ପଦ୍ଧତି','Reset':'ରିସେଟ୍','CivicLink Assistant':'CivicLink ସହାୟକ','Type your answer...':'ଆପଣଙ୍କ ଉତ୍ତର ଲେଖନ୍ତୁ...','Voice input':'ଭଏସ୍ ଇନପୁଟ୍','This page does not exist.':'ଏହି ପୃଷ୍ଠା ନାହିଁ.'},
  as: {'Home':'হোম','Explore Schemes':'আঁচনিসমূহ চাওক','Smart Matching':'স্মাৰ্ট মিল','Financial Calculator':'বিত্তীয় কেলকুলেটৰ','Find Nearby Partner':'ওচৰৰ অংশীদাৰ বিচাৰক','More':'অধিক','Citizen Login':'নাগৰিক লগইন','Register':'পঞ্জীয়ন','Official':'চৰকাৰী','All Schemes Directory':'সকলো আঁচনিৰ তালিকা','Verified':'সত্যাপিত','Call':'কল','Directions':'দিশ-নিৰ্দেশ','Use My Location':'মোৰ অৱস্থান ব্যৱহাৰ কৰক','Scheme not found':'আঁচনি পোৱা নগল','Back to Directory':'তালিকালৈ উভতি যাওক','Government Verified':'চৰকাৰীভাৱে সত্যাপিত','Eligibility Criteria':'যোগ্যতাৰ মাপকাঠী','Required Documents':'প্ৰয়োজনীয় নথি','Ready to Apply?':'আবেদন কৰিবলৈ সাজু?','Find Partner':'অংশীদাৰ বিচাৰক','Apply on Portal':'পৰ্টেলত আবেদন কৰক','Max Support / Loan':'সৰ্বাধিক সহায় / ঋণ','Interest Rate':'সুতৰ হাৰ','Application Route':'আবেদনৰ পদ্ধতি','Reset':'ৰিছেট','CivicLink Assistant':'CivicLink সহায়ক','Type your answer...':'আপোনাৰ উত্তৰ লিখক...','Voice input':'ভইচ ইনপুট','This page does not exist.':'এই পৃষ্ঠা নাই.'}
};

const LANGUAGE_VOICE = { en:'en-IN', hi:'hi-IN', bn:'bn-IN', ta:'ta-IN', te:'te-IN', mr:'mr-IN', gu:'gu-IN', kn:'kn-IN', ml:'ml-IN', pa:'pa-IN', or:'or-IN', as:'as-IN' };

export const LANG_CODES = Object.fromEntries(LANGUAGES.map(l => [l.code, l.label]));
export const voiceLocale = (code) => LANGUAGE_VOICE[code] || 'en-IN';
export const translate = (code, text) => (DICT[code] && DICT[code][text]) || DICT.en[text] || text;

const LanguageContext = createContext({ language:'en', setLanguage:()=>{}, t:(x)=>x });

export function LanguageProvider({ language, setLanguage, children }) {
  const t = useMemo(() => (text) => translate(language, text), [language]);
  useEffect(() => {
    document.documentElement.lang = language;
    try { localStorage.setItem('civiclink_language', language); } catch(e) {}
  }, [language]);
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
