import React, { createContext, useContext, useEffect, useMemo } from 'react';
import { LANGUAGES } from './mock';

const DICT = {
  en: {
    'GOVT OF INDIA':'GOVT OF INDIA','National Welfare & Credit Guidance Platform':'National Welfare & Credit Guidance Platform',
    'Helpline: 1800-11-2026 (Toll-Free)':'Helpline: 1800-11-2026 (Toll-Free)','Government Citizen Platform':'Government Citizen Platform',
    'Home':'Home','Explore Schemes':'Explore Schemes','Smart Matching':'Smart Matching','Financial Calculator':'Financial Calculator',
    'Find Nearby Partner':'Find Nearby Partner','More':'More','Citizen Login':'Citizen Login','Register':'Register',
    'Official':'Official','Decrease font size':'Decrease font size','Reset font size':'Reset font size','Increase font size':'Increase font size',
    'All Schemes Directory':'All Schemes Directory','Smart Scheme Matching':'Smart Scheme Matching','Loan & Subsidy Calculator':'Loan & Subsidy Calculator',
    'Nearby Partner Centers':'Nearby Partner Centers','Sign In / Portal':'Sign In / Portal','QUICK LINKS':'QUICK LINKS',
    'SUPPORT & HELPLINE':'SUPPORT & HELPLINE','GOVERNANCE & TRUST':'GOVERNANCE & TRUST','Verified':'Verified','Call':'Call','Directions':'Directions',
    'Use My Location':'Use My Location','No partners found for your search.':'No partners found for your search.',
    'Scheme not found':'Scheme not found','Back to Directory':'Back to Directory','Government Verified':'Government Verified',
    'Eligibility Criteria':'Eligibility Criteria','Required Documents':'Required Documents','Ready to Apply?':'Ready to Apply?',
    'Find Partner':'Find Partner','Apply on Portal':'Apply on Portal','Max Support / Loan':'Max Support / Loan','Interest Rate':'Interest Rate',
    'Application Route':'Application Route','Reset':'Reset','CivicLink Assistant':'CivicLink Assistant','Rule-based scheme guidance':'Rule-based scheme guidance',
    'Analyzing your profile against 90 government schemes...':'Analyzing your profile against 90 government schemes...',
    'Type your answer...':'Type your answer...','Voice input':'Voice input','This page does not exist.':'This page does not exist.',
    'Authentication is optional. You can use CivicLink without an account.':'Authentication is optional. You can use CivicLink without an account.',
    'Mobile number':'Mobile number','Password / OTP':'Password / OTP'
  },
  hi: {
    'GOVT OF INDIA':'भारत सरकार','National Welfare & Credit Guidance Platform':'राष्ट्रीय कल्याण एवं ऋण मार्गदर्शन मंच','Helpline: 1800-11-2026 (Toll-Free)':'हेल्पलाइन: 1800-11-2026 (टोल-फ्री)',
    'Government Citizen Platform':'सरकारी नागरिक मंच','Home':'होम','Explore Schemes':'योजनाएँ देखें','Smart Matching':'स्मार्ट मिलान','Financial Calculator':'वित्तीय कैलकुलेटर','Find Nearby Partner':'नज़दीकी साझेदार खोजें','More':'अधिक','Citizen Login':'नागरिक लॉगिन','Register':'पंजीकरण','Official':'आधिकारिक',
    'All Schemes Directory':'सभी योजनाओं की सूची','Smart Scheme Matching':'स्मार्ट योजना मिलान','Loan & Subsidy Calculator':'ऋण एवं सब्सिडी कैलकुलेटर','Nearby Partner Centers':'नज़दीकी साझेदार केंद्र','Sign In / Portal':'साइन इन / पोर्टल','QUICK LINKS':'त्वरित लिंक','SUPPORT & HELPLINE':'सहायता एवं हेल्पलाइन','GOVERNANCE & TRUST':'शासन एवं विश्वास','Verified':'सत्यापित','Call':'कॉल','Directions':'दिशा-निर्देश','Use My Location':'मेरी लोकेशन इस्तेमाल करें','No partners found for your search.':'आपकी खोज के लिए कोई साझेदार नहीं मिला।','Scheme not found':'योजना नहीं मिली','Back to Directory':'सूची पर वापस जाएँ','Government Verified':'सरकार द्वारा सत्यापित','Eligibility Criteria':'पात्रता मानदंड','Required Documents':'आवश्यक दस्तावेज़','Ready to Apply?':'आवेदन के लिए तैयार?','Find Partner':'साझेदार खोजें','Apply on Portal':'पोर्टल पर आवेदन करें','Max Support / Loan':'अधिकतम सहायता / ऋण','Interest Rate':'ब्याज दर','Application Route':'आवेदन का तरीका','Reset':'रीसेट','CivicLink Assistant':'सिविक लिंक सहायक','Rule-based scheme guidance':'नियम-आधारित योजना मार्गदर्शन','Analyzing your profile against 90 government schemes...':'90 सरकारी योजनाओं के अनुसार आपकी प्रोफ़ाइल का विश्लेषण हो रहा है...','Type your answer...':'अपना उत्तर लिखें...','Voice input':'आवाज़ से इनपुट','This page does not exist.':'यह पेज मौजूद नहीं है।','Authentication is optional. You can use CivicLink without an account.':'प्रमाणीकरण वैकल्पिक है। आप बिना खाते के CivicLink का उपयोग कर सकते हैं।','Mobile number':'मोबाइल नंबर','Password / OTP':'पासवर्ड / OTP'
  },
  bn: {'Home':'হোম','Explore Schemes':'প্রকল্প দেখুন','Smart Matching':'স্মার্ট ম্যাচিং','Financial Calculator':'আর্থিক ক্যালকুলেটর','Find Nearby Partner':'কাছের অংশীদার খুঁজুন','More':'আরও','Citizen Login':'নাগরিক লগইন','Register':'নিবন্ধন','Official':'সরকারি','All Schemes Directory':'সব প্রকল্পের তালিকা','Smart Scheme Matching':'স্মার্ট প্রকল্প ম্যাচিং','Loan & Subsidy Calculator':'ঋণ ও ভর্তুকি ক্যালকুলেটর','Verified':'যাচাইকৃত','Call':'কল','Directions':'দিকনির্দেশ','Use My Location':'আমার অবস্থান ব্যবহার করুন','No partners found for your search.':'আপনার অনুসন্ধানে কোনো অংশীদার পাওয়া যায়নি।','Scheme not found':'প্রকল্প পাওয়া যায়নি','Back to Directory':'তালিকায় ফিরুন','Government Verified':'সরকারি যাচাইকৃত','Eligibility Criteria':'যোগ্যতার মানদণ্ড','Required Documents':'প্রয়োজনীয় নথি','Ready to Apply?':'আবেদন করতে প্রস্তুত?','Find Partner':'অংশীদার খুঁজুন','Apply on Portal':'পোর্টালে আবেদন করুন','Max Support / Loan':'সর্বোচ্চ সহায়তা / ঋণ','Interest Rate':'সুদের হার','Application Route':'আবেদনের পদ্ধতি','Reset':'রিসেট','CivicLink Assistant':'CivicLink সহায়ক','Type your answer...':'আপনার উত্তর লিখুন...','Voice input':'ভয়েস ইনপুট','This page does not exist.':'এই পৃষ্ঠাটি নেই।'},
  ta: {'Home':'முகப்பு','Explore Schemes':'திட்டங்களைப் பார்க்க','Smart Matching':'ஸ்மார்ட் பொருத்தம்','Financial Calculator':'நிதி கணிப்பான்','Find Nearby Partner':'அருகிலுள்ள கூட்டாளரைத் தேடு','More':'மேலும்','Citizen Login':'குடிமக்கள் உள்நுழைவு','Register':'பதிவு','Official':'அதிகாரப்பூர்வ','All Schemes Directory':'அனைத்து திட்டங்கள்','Verified':'சரிபார்க்கப்பட்டது','Call':'அழைப்பு','Directions':'வழிகள்','Use My Location':'என் இருப்பிடத்தைப் பயன்படுத்து','Scheme not found':'திட்டம் கிடைக்கவில்லை','Back to Directory':'பட்டியலுக்குத் திரும்பு','Government Verified':'அரசால் சரிபார்க்கப்பட்டது','Eligibility Criteria':'தகுதி அளவுகோல்கள்','Required Documents':'தேவையான ஆவணங்கள்','Ready to Apply?':'விண்ணப்பிக்கத் தயாரா?','Find Partner':'கூட்டாளரைக் கண்டுபிடி','Apply on Portal':'போர்டலில் விண்ணப்பி','Max Support / Loan':'அதிகபட்ச உதவி / கடன்','Interest Rate':'வட்டி விகிதம்','Application Route':'விண்ணப்ப முறை','Reset':'மீட்டமை','CivicLink Assistant':'CivicLink உதவியாளர்','Type your answer...':'உங்கள் பதிலை உள்ளிடவும்...','Voice input':'குரல் உள்ளீடு','This page does not exist.':'இந்தப் பக்கம் இல்லை.'},
  te: {'Home':'హోమ్','Explore Schemes':'పథకాలను చూడండి','Smart Matching':'స్మార్ట్ మ్యాచ్','Financial Calculator':'ఆర్థిక కాలిక్యులేటర్','Find Nearby Partner':'సమీప భాగస్వామిని కనుగొనండి','More':'మరిన్ని','Citizen Login':'పౌర లాగిన్','Register':'నమోదు','Official':'అధికారిక','All Schemes Directory':'అన్ని పథకాల జాబితా','Verified':'ధృవీకరించబడింది','Call':'కాల్','Directions':'దిశలు','Use My Location':'నా స్థానాన్ని ఉపయోగించండి','Scheme not found':'పథకం కనబడలేదు','Back to Directory':'జాబితాకు తిరిగి వెళ్లండి','Government Verified':'ప్రభుత్వ ధృవీకరణ','Eligibility Criteria':'అర్హత ప్రమాణాలు','Required Documents':'అవసరమైన పత్రాలు','Ready to Apply?':'దరఖాస్తు చేయడానికి సిద్ధంగా ఉన్నారా?','Find Partner':'భాగస్వామిని కనుగొనండి','Apply on Portal':'పోర్టల్‌లో దరఖాస్తు చేయండి','Max Support / Loan':'గరిష్ఠ సహాయం / రుణం','Interest Rate':'వడ్డీ రేటు','Application Route':'దరఖాస్తు విధానం','Reset':'రీసెట్','CivicLink Assistant':'CivicLink సహాయకుడు','Type your answer...':'మీ సమాధానాన్ని టైప్ చేయండి...','Voice input':'వాయిస్ ఇన్‌పుట్','This page does not exist.':'ఈ పేజీ లేదు.'},
  mr: {'Home':'मुख्यपृष्ठ','Explore Schemes':'योजना पहा','Smart Matching':'स्मार्ट जुळणी','Financial Calculator':'आर्थिक कॅल्क्युलेटर','Find Nearby Partner':'जवळचा भागीदार शोधा','More':'अधिक','Citizen Login':'नागरिक लॉगिन','Register':'नोंदणी','Official':'अधिकृत','All Schemes Directory':'सर्व योजनांची यादी','Verified':'सत्यापित','Call':'कॉल','Directions':'दिशा','Use My Location':'माझे स्थान वापरा','Scheme not found':'योजना सापडली नाही','Back to Directory':'यादीकडे परत जा','Government Verified':'सरकारद्वारे सत्यापित','Eligibility Criteria':'पात्रता निकष','Required Documents':'आवश्यक कागदपत्रे','Ready to Apply?':'अर्ज करण्यास तयार आहात?','Find Partner':'भागीदार शोधा','Apply on Portal':'पोर्टलवर अर्ज करा','Max Support / Loan':'कमाल मदत / कर्ज','Interest Rate':'व्याजदर','Application Route':'अर्ज पद्धत','Reset':'रीसेट','CivicLink Assistant':'CivicLink सहाय्यक','Type your answer...':'तुमचे उत्तर टाइप करा...','Voice input':'व्हॉइस इनपुट','This page does not exist.':'हे पृष्ठ अस्तित्वात नाही.'},
  gu: {'Home':'હોમ','Explore Schemes':'યોજનાઓ જુઓ','Smart Matching':'સ્માર્ટ મેચિંગ','Financial Calculator':'નાણાકીય કેલ્ક્યુલેટર','Find Nearby Partner':'નજીકનો ભાગીદાર શોધો','More':'વધુ','Citizen Login':'નાગરિક લૉગિન','Register':'નોંધણી','Official':'સત્તાવાર','All Schemes Directory':'તમામ યોજનાઓની યાદી','Verified':'ચકાસાયેલ','Call':'કૉલ','Directions':'દિશા-નિર્દેશ','Use My Location':'મારું સ્થાન વાપરો','Scheme not found':'યોજના મળી નથી','Back to Directory':'યાદી પર પાછા જાઓ','Government Verified':'સરકાર દ્વારા ચકાસાયેલ','Eligibility Criteria':'પાત્રતા માપદંડ','Required Documents':'જરૂરી દસ્તાવેજો','Ready to Apply?':'અરજી કરવા તૈયાર છો?','Find Partner':'ભાગીદાર શોધો','Apply on Portal':'પોર્ટલ પર અરજી કરો','Max Support / Loan':'મહત્તમ સહાય / લોન','Interest Rate':'વ્યાજ દર','Application Route':'અરજીનો માર્ગ','Reset':'રીસેટ','CivicLink Assistant':'CivicLink સહાયક','Type your answer...':'તમારો જવાબ લખો...','Voice input':'વૉઇસ ઇનપુટ','This page does not exist.':'આ પૃષ્ઠ અસ્તિત્વમાં નથી.'},
  kn: {'Home':'ಮುಖಪುಟ','Explore Schemes':'ಯೋಜನೆಗಳನ್ನು ನೋಡಿ','Smart Matching':'ಸ್ಮಾರ್ಟ್ ಹೊಂದಾಣಿಕೆ','Financial Calculator':'ಹಣಕಾಸು ಕ್ಯಾಲ್ಕುಲೇಟರ್','Find Nearby Partner':'ಹತ್ತಿರದ ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ','More':'ಇನ್ನಷ್ಟು','Citizen Login':'ನಾಗರಿಕ ಲಾಗಿನ್','Register':'ನೋಂದಣಿ','Official':'ಅಧಿಕೃತ','All Schemes Directory':'ಎಲ್ಲಾ ಯೋಜನೆಗಳ ಪಟ್ಟಿ','Verified':'ಪರಿಶೀಲಿಸಲಾಗಿದೆ','Call':'ಕರೆ','Directions':'ದಿಕ್ಕುಗಳು','Use My Location':'ನನ್ನ ಸ್ಥಳ ಬಳಸಿ','Scheme not found':'ಯೋಜನೆ ಕಂಡುಬಂದಿಲ್ಲ','Back to Directory':'ಪಟ್ಟಿಗೆ ಹಿಂತಿರುಗಿ','Government Verified':'ಸರ್ಕಾರದಿಂದ ಪರಿಶೀಲಿಸಲಾಗಿದೆ','Eligibility Criteria':'ಅರ್ಹತಾ ಮಾನದಂಡಗಳು','Required Documents':'ಅಗತ್ಯ ದಾಖಲೆಗಳು','Ready to Apply?':'ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಸಿದ್ಧವೇ?','Find Partner':'ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ','Apply on Portal':'ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ','Max Support / Loan':'ಗರಿಷ್ಠ ಸಹಾಯ / ಸಾಲ','Interest Rate':'ಬಡ್ಡಿ ದರ','Application Route':'ಅರ್ಜಿ ವಿಧಾನ','Reset':'ಮರುಹೊಂದಿಸಿ','CivicLink Assistant':'CivicLink ಸಹಾಯಕ','Type your answer...':'ನಿಮ್ಮ ಉತ್ತರವನ್ನು ಟೈಪ್ ಮಾಡಿ...','Voice input':'ಧ್ವನಿ ಇನ್‌ಪುಟ್','This page does not exist.':'ಈ ಪುಟ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ.'},
  ml: {'Home':'ഹോം','Explore Schemes':'പദ്ധതികൾ കാണുക','Smart Matching':'സ്മാർട്ട് മാച്ചിംഗ്','Financial Calculator':'സാമ്പത്തിക കാൽക്കുലേറ്റർ','Find Nearby Partner':'അടുത്തുള്ള പങ്കാളിയെ കണ്ടെത്തുക','More':'കൂടുതൽ','Citizen Login':'പൗര ലോഗിൻ','Register':'രജിസ്റ്റർ','Official':'ഔദ്യോഗിക','All Schemes Directory':'എല്ലാ പദ്ധതികളുടെയും പട്ടിക','Verified':'പരിശോധിച്ചത്','Call':'വിളിക്കുക','Directions':'ദിശകൾ','Use My Location':'എന്റെ സ്ഥലം ഉപയോഗിക്കുക','Scheme not found':'പദ്ധതി കണ്ടെത്തിയില്ല','Back to Directory':'പട്ടികയിലേക്ക് മടങ്ങുക','Government Verified':'സർക്കാർ പരിശോധിച്ചത്','Eligibility Criteria':'യോഗ്യതാ മാനദണ്ഡങ്ങൾ','Required Documents':'ആവശ്യമായ രേഖകൾ','Ready to Apply?':'അപേക്ഷിക്കാൻ തയ്യാറാണോ?','Find Partner':'പങ്കാളിയെ കണ്ടെത്തുക','Apply on Portal':'പോർട്ടലിൽ അപേക്ഷിക്കുക','Max Support / Loan':'പരമാവധി സഹായം / വായ്പ','Interest Rate':'പലിശ നിരക്ക്','Application Route':'അപേക്ഷാ മാർഗം','Reset':'റീസെറ്റ്','CivicLink Assistant':'CivicLink സഹായി','Type your answer...':'നിങ്ങളുടെ ഉത്തരം ടൈപ്പ് ചെയ്യുക...','Voice input':'വോയ്സ് ഇൻപുട്ട്','This page does not exist.':'ഈ പേജ് നിലവിലില്ല.'},
  pa: {'Home':'ਹੋਮ','Explore Schemes':'ਸਕੀਮਾਂ ਵੇਖੋ','Smart Matching':'ਸਮਾਰਟ ਮੈਚਿੰਗ','Financial Calculator':'ਵਿੱਤੀ ਕੈਲਕੁਲੇਟਰ','Find Nearby Partner':'ਨੇੜਲਾ ਭਾਈਵਾਲ ਲੱਭੋ','More':'ਹੋਰ','Citizen Login':'ਨਾਗਰਿਕ ਲੌਗਇਨ','Register':'ਰਜਿਸਟਰ','Official':'ਅਧਿਕਾਰਤ','All Schemes Directory':'ਸਾਰੀਆਂ ਸਕੀਮਾਂ ਦੀ ਸੂਚੀ','Verified':'ਪ੍ਰਮਾਣਿਤ','Call':'ਕਾਲ','Directions':'ਦਿਸ਼ਾਵਾਂ','Use My Location':'ਮੇਰੀ ਸਥਿਤੀ ਵਰਤੋ','Scheme not found':'ਸਕੀਮ ਨਹੀਂ ਮਿਲੀ','Back to Directory':'ਸੂਚੀ ਤੇ ਵਾਪਸ ਜਾਓ','Government Verified':'ਸਰਕਾਰ ਵੱਲੋਂ ਪ੍ਰਮਾਣਿਤ','Eligibility Criteria':'ਯੋਗਤਾ ਮਾਪਦੰਡ','Required Documents':'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼','Ready to Apply?':'ਅਰਜ਼ੀ ਲਈ ਤਿਆਰ ਹੋ?','Find Partner':'ਭਾਈਵਾਲ ਲੱਭੋ','Apply on Portal':'ਪੋਰਟਲ ਤੇ ਅਰਜ਼ੀ ਦਿਓ','Max Support / Loan':'ਵੱਧ ਤੋਂ ਵੱਧ ਸਹਾਇਤਾ / ਕਰਜ਼ਾ','Interest Rate':'ਵਿਆਜ ਦਰ','Application Route':'ਅਰਜ਼ੀ ਦਾ ਰਸਤਾ','Reset':'ਰੀਸੈੱਟ','CivicLink Assistant':'CivicLink ਸਹਾਇਕ','Type your answer...':'ਆਪਣਾ ਜਵਾਬ ਲਿਖੋ...','Voice input':'ਆਵਾਜ਼ ਇਨਪੁੱਟ','This page does not exist.':'ਇਹ ਪੰਨਾ ਮੌਜੂਦ ਨਹੀਂ ਹੈ.'},
  or: {'Home':'ମୁଖ୍ୟ ପୃଷ୍ଠା','Explore Schemes':'ଯୋଜନା ଦେଖନ୍ତୁ','Smart Matching':'ସ୍ମାର୍ଟ ମ୍ୟାଚିଂ','Financial Calculator':'ଆର୍ଥିକ କ୍ୟାଲକୁଲେଟର','Find Nearby Partner':'ନିକଟସ୍ଥ ସହଭାଗୀ ଖୋଜନ୍ତୁ','More':'ଅଧିକ','Citizen Login':'ନାଗରିକ ଲଗଇନ','Register':'ପଞ୍ଜୀକରଣ','Official':'ସରକାରୀ','All Schemes Directory':'ସମସ୍ତ ଯୋଜନା ତାଲିକା','Verified':'ଯାଞ୍ଚିତ','Call':'କଲ୍','Directions':'ଦିଗନିର୍ଦ୍ଦେଶ','Use My Location':'ମୋ ଅବସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ','Scheme not found':'ଯୋଜନା ମିଳିଲା ନାହିଁ','Back to Directory':'ତାଲିକାକୁ ଫେରନ୍ତୁ','Government Verified':'ସରକାରୀ ଯାଞ୍ଚିତ','Eligibility Criteria':'ଯୋଗ୍ୟତା ମାନଦଣ୍ଡ','Required Documents':'ଆବଶ୍ୟକ ଦଲିଲ','Ready to Apply?':'ଆବେଦନ ପାଇଁ ପ୍ରସ୍ତୁତ?','Find Partner':'ସହଭାଗୀ ଖୋଜନ୍ତୁ','Apply on Portal':'ପୋର୍ଟାଲରେ ଆବେଦନ କରନ୍ତୁ','Max Support / Loan':'ସର୍ବାଧିକ ସହାୟତା / ଋଣ','Interest Rate':'ସୁଧ ହାର','Application Route':'ଆବେଦନ ପଦ୍ଧତି','Reset':'ରିସେଟ୍','CivicLink Assistant':'CivicLink ସହାୟକ','Type your answer...':'ଆପଣଙ୍କ ଉତ୍ତର ଲେଖନ୍ତୁ...','Voice input':'ଭଏସ୍ ଇନପୁଟ୍','This page does not exist.':'ଏହି ପୃଷ୍ଠା ନାହିଁ.'},
  as: {'Home':'হোম','Explore Schemes':'আঁচনিসমূহ চাওক','Smart Matching':'স্মাৰ্ট মিল','Financial Calculator':'বিত্তীয় কেলকুলেটৰ','Find Nearby Partner':'ওচৰৰ অংশীদাৰ বিচাৰক','More':'অধিক','Citizen Login':'নাগৰিক লগইন','Register':'পঞ্জীয়ন','Official':'চৰকাৰী','All Schemes Directory':'সকলো আঁচনিৰ তালিকা','Verified':'সত্যাপিত','Call':'কল','Directions':'দিশ-নিৰ্দেশ','Use My Location':'মোৰ অৱস্থান ব্যৱহাৰ কৰক','Scheme not found':'আঁচনি পোৱা নগল','Back to Directory':'তালিকালৈ উভতি যাওক','Government Verified':'চৰকাৰীভাৱে সত্যাপিত','Eligibility Criteria':'যোগ্যতাৰ মাপকাঠী','Required Documents':'প্ৰয়োজনীয় নথি','Ready to Apply?':'আবেদন কৰিবলৈ সাজু?','Find Partner':'অংশীদাৰ বিচাৰক','Apply on Portal':'পৰ্টেলত আবেদন কৰক','Max Support / Loan':'সৰ্বাধিক সহায় / ঋণ','Interest Rate':'সুতৰ হাৰ','Application Route':'আবেদনৰ পদ্ধতি','Reset':'ৰিছেট','CivicLink Assistant':'CivicLink সহায়ক','Type your answer...':'আপোনাৰ উত্তৰ লিখক...','Voice input':'ভইচ ইনপুট','This page does not exist.':'এই পৃষ্ঠা নাই.'}
};


// Conversational assistant localization. Keys stay in English so profile values sent to the backend remain canonical.
const CHAT_I18N = {
  hi: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'नमस्ते! मैं CivicLink सहायक हूँ। क्या मैं आपका नाम जान सकता हूँ?','Thank you. What is your age in years?':'धन्यवाद। आपकी आयु कितने वर्ष है?','Please share your gender.':'कृपया अपना लिंग बताएं।','Which social category do you belong to?':'आप किस सामाजिक श्रेणी से संबंधित हैं?','What is your approximate annual family income (₹)?':'आपकी अनुमानित वार्षिक पारिवारिक आय कितनी है (₹)?','What best describes your occupation?':'आपके व्यवसाय का सबसे सही वर्णन क्या है?','Which state do you live in?':'आप किस राज्य में रहते हैं?','What kind of support are you looking for?':'आप किस प्रकार की सहायता चाहते हैं?','Your full name':'अपना पूरा नाम','e.g. 28':'जैसे 28'
  },
  bn: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'নমস্কার! আমি CivicLink সহায়ক। আপনার নাম জানতে পারি?','Thank you. What is your age in years?':'ধন্যবাদ। আপনার বয়স কত বছর?','Please share your gender.':'অনুগ্রহ করে আপনার লিঙ্গ জানান।','Which social category do you belong to?':'আপনি কোন সামাজিক শ্রেণির অন্তর্ভুক্ত?','What is your approximate annual family income (₹)?':'আপনার আনুমানিক বার্ষিক পারিবারিক আয় কত (₹)?','What best describes your occupation?':'আপনার পেশাকে সবচেয়ে ভালোভাবে কী বর্ণনা করে?','Which state do you live in?':'আপনি কোন রাজ্যে থাকেন?','What kind of support are you looking for?':'আপনি কী ধরনের সহায়তা চান?','Your full name':'আপনার পুরো নাম','e.g. 28':'যেমন ২৮'
  },
  ta: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'வணக்கம்! நான் CivicLink உதவியாளர். உங்கள் பெயரை அறியலாமா?','Thank you. What is your age in years?':'நன்றி. உங்கள் வயது எத்தனை ஆண்டுகள்?','Please share your gender.':'உங்கள் பாலினத்தைப் பகிரவும்.','Which social category do you belong to?':'நீங்கள் எந்த சமூகப் பிரிவைச் சேர்ந்தவர்?','What is your approximate annual family income (₹)?':'உங்கள் குடும்பத்தின் தோராயமான ஆண்டு வருமானம் என்ன (₹)?','What best describes your occupation?':'உங்கள் தொழிலை எது சிறப்பாக விவரிக்கிறது?','Which state do you live in?':'நீங்கள் எந்த மாநிலத்தில் வசிக்கிறீர்கள்?','What kind of support are you looking for?':'நீங்கள் எந்த வகையான உதவியைத் தேடுகிறீர்கள்?','Your full name':'உங்கள் முழுப் பெயர்','e.g. 28':'எ.கா. 28'
  },
  te: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'నమస్తే! నేను CivicLink సహాయకుడిని. మీ పేరు తెలుసుకోవచ్చా?','Thank you. What is your age in years?':'ధన్యవాదాలు. మీ వయస్సు ఎంత?','Please share your gender.':'దయచేసి మీ లింగాన్ని తెలియజేయండి.','Which social category do you belong to?':'మీరు ఏ సామాజిక వర్గానికి చెందుతారు?','What is your approximate annual family income (₹)?':'మీ కుటుంబ వార్షిక ఆదాయం సుమారుగా ఎంత (₹)?','What best describes your occupation?':'మీ వృత్తిని ఏది ఉత్తమంగా వివరిస్తుంది?','Which state do you live in?':'మీరు ఏ రాష్ట్రంలో నివసిస్తున్నారు?','What kind of support are you looking for?':'మీరు ఎలాంటి సహాయం కోరుతున్నారు?','Your full name':'మీ పూర్తి పేరు','e.g. 28':'ఉదా. 28'
  },
  mr: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'नमस्कार! मी CivicLink सहाय्यक आहे. तुमचे नाव सांगाल का?','Thank you. What is your age in years?':'धन्यवाद. तुमचे वय किती वर्षे आहे?','Please share your gender.':'कृपया तुमचे लिंग सांगा.','Which social category do you belong to?':'तुम्ही कोणत्या सामाजिक श्रेणीतील आहात?','What is your approximate annual family income (₹)?':'तुमचे अंदाजे वार्षिक कौटुंबिक उत्पन्न किती आहे (₹)?','What best describes your occupation?':'तुमच्या व्यवसायाचे सर्वात योग्य वर्णन कोणते?','Which state do you live in?':'तुम्ही कोणत्या राज्यात राहता?','What kind of support are you looking for?':'तुम्ही कोणत्या प्रकारची मदत शोधत आहात?','Your full name':'तुमचे पूर्ण नाव','e.g. 28':'उदा. 28'
  },
  gu: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'નમસ્તે! હું CivicLink સહાયક છું. શું હું તમારું નામ જાણી શકું?','Thank you. What is your age in years?':'આભાર. તમારી ઉંમર કેટલી છે?','Please share your gender.':'કૃપા કરીને તમારું લિંગ જણાવો.','Which social category do you belong to?':'તમે કઈ સામાજિક શ્રેણી સાથે સંબંધિત છો?','What is your approximate annual family income (₹)?':'તમારી અંદાજિત વાર્ષિક કૌટુંબિક આવક કેટલી છે (₹)?','What best describes your occupation?':'તમારા વ્યવસાયનું સૌથી યોગ્ય વર્ણન શું છે?','Which state do you live in?':'તમે કયા રાજ્યમાં રહો છો?','What kind of support are you looking for?':'તમે કયા પ્રકારની સહાય શોધી રહ્યા છો?','Your full name':'તમારું પૂરું નામ','e.g. 28':'જેમ કે 28'
  },
  kn: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'ನಮಸ್ಕಾರ! ನಾನು CivicLink ಸಹಾಯಕ. ನಿಮ್ಮ ಹೆಸರು ತಿಳಿಸಬಹುದೇ?','Thank you. What is your age in years?':'ಧನ್ಯವಾದಗಳು. ನಿಮ್ಮ ವಯಸ್ಸು ಎಷ್ಟು?','Please share your gender.':'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಲಿಂಗವನ್ನು ತಿಳಿಸಿ.','Which social category do you belong to?':'ನೀವು ಯಾವ ಸಾಮಾಜಿಕ ವರ್ಗಕ್ಕೆ ಸೇರಿದವರು?','What is your approximate annual family income (₹)?':'ನಿಮ್ಮ ಅಂದಾಜು ವಾರ್ಷಿಕ ಕುಟುಂಬ ಆದಾಯ ಎಷ್ಟು (₹)?','What best describes your occupation?':'ನಿಮ್ಮ ಉದ್ಯೋಗವನ್ನು ಯಾವುದು ಉತ್ತಮವಾಗಿ ವಿವರಿಸುತ್ತದೆ?','Which state do you live in?':'ನೀವು ಯಾವ ರಾಜ್ಯದಲ್ಲಿ ವಾಸಿಸುತ್ತೀರಿ?','What kind of support are you looking for?':'ನೀವು ಯಾವ ರೀತಿಯ ಸಹಾಯವನ್ನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ?','Your full name':'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು','e.g. 28':'ಉದಾ. 28'
  },
  ml: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'നമസ്കാരം! ഞാൻ CivicLink സഹായി. നിങ്ങളുടെ പേര് അറിയാമോ?','Thank you. What is your age in years?':'നന്ദി. നിങ്ങളുടെ പ്രായം എത്രയാണ്?','Please share your gender.':'ദയവായി നിങ്ങളുടെ ലിംഗം അറിയിക്കുക.','Which social category do you belong to?':'നിങ്ങൾ ഏത് സാമൂഹിക വിഭാഗത്തിൽപ്പെടുന്നു?','What is your approximate annual family income (₹)?':'നിങ്ങളുടെ ഏകദേശ വാർഷിക കുടുംബവരുമാനം എത്രയാണ് (₹)?','What best describes your occupation?':'നിങ്ങളുടെ തൊഴിൽ ഏതാണ് ഏറ്റവും നന്നായി വിവരിക്കുന്നത്?','Which state do you live in?':'നിങ്ങൾ ഏത് സംസ്ഥാനത്താണ് താമസിക്കുന്നത്?','What kind of support are you looking for?':'നിങ്ങൾ ഏത് തരത്തിലുള്ള സഹായമാണ് തേടുന്നത്?','Your full name':'നിങ്ങളുടെ പൂർണ്ണ പേര്','e.g. 28':'ഉദാ. 28'
  },
  pa: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ CivicLink ਸਹਾਇਕ ਹਾਂ। ਕੀ ਮੈਂ ਤੁਹਾਡਾ ਨਾਮ ਜਾਣ ਸਕਦਾ ਹਾਂ?','Thank you. What is your age in years?':'ਧੰਨਵਾਦ। ਤੁਹਾਡੀ ਉਮਰ ਕਿੰਨੀ ਹੈ?','Please share your gender.':'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਲਿੰਗ ਦੱਸੋ।','Which social category do you belong to?':'ਤੁਸੀਂ ਕਿਸ ਸਮਾਜਿਕ ਸ਼੍ਰੇਣੀ ਨਾਲ ਸਬੰਧਤ ਹੋ?','What is your approximate annual family income (₹)?':'ਤੁਹਾਡੀ ਲਗਭਗ ਸਾਲਾਨਾ ਪਰਿਵਾਰਕ ਆਮਦਨ ਕਿੰਨੀ ਹੈ (₹)?','What best describes your occupation?':'ਤੁਹਾਡੇ ਕਿੱਤੇ ਦਾ ਸਭ ਤੋਂ ਵਧੀਆ ਵਰਣਨ ਕੀ ਹੈ?','Which state do you live in?':'ਤੁਸੀਂ ਕਿਸ ਰਾਜ ਵਿੱਚ ਰਹਿੰਦੇ ਹੋ?','What kind of support are you looking for?':'ਤੁਸੀਂ ਕਿਸ ਕਿਸਮ ਦੀ ਸਹਾਇਤਾ ਚਾਹੁੰਦੇ ਹੋ?','Your full name':'ਤੁਹਾਡਾ ਪੂਰਾ ਨਾਮ','e.g. 28':'ਜਿਵੇਂ 28'
  },
  or: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'ନମସ୍କାର! ମୁଁ CivicLink ସହାୟକ। ଆପଣଙ୍କ ନାମ ଜାଣିପାରିବି କି?','Thank you. What is your age in years?':'ଧନ୍ୟବାଦ। ଆପଣଙ୍କ ବୟସ କେତେ?','Please share your gender.':'ଦୟାକରି ଆପଣଙ୍କ ଲିଙ୍ଗ କୁହନ୍ତୁ।','Which social category do you belong to?':'ଆପଣ କେଉଁ ସାମାଜିକ ବର୍ଗର?','What is your approximate annual family income (₹)?':'ଆପଣଙ୍କ ଆନୁମାନିକ ବାର୍ଷିକ ପରିବାର ଆୟ କେତେ (₹)?','What best describes your occupation?':'ଆପଣଙ୍କ ବୃତ୍ତିକୁ କେଉଁଟି ଭଲଭାବେ ବର୍ଣ୍ଣନା କରେ?','Which state do you live in?':'ଆପଣ କେଉଁ ରାଜ୍ୟରେ ରହୁଛନ୍ତି?','What kind of support are you looking for?':'ଆପଣ କେଉଁ ପ୍ରକାର ସହାୟତା ଚାହୁଁଛନ୍ତି?','Your full name':'ଆପଣଙ୍କ ସମ୍ପୂର୍ଣ୍ଣ ନାମ','e.g. 28':'ଯଥା 28'
  },
  as: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'নমস্কাৰ! মই CivicLink সহায়ক। আপোনাৰ নাম জানিব পাৰোঁনে?','Thank you. What is your age in years?':'ধন্যবাদ। আপোনাৰ বয়স কিমান বছৰ?','Please share your gender.':'অনুগ্ৰহ কৰি আপোনাৰ লিংগ জনাওক।','Which social category do you belong to?':'আপুনি কোন সামাজিক শ্ৰেণীৰ অন্তৰ্গত?','What is your approximate annual family income (₹)?':'আপোনাৰ আনুমানিক বাৰ্ষিক পৰিয়ালৰ আয় কিমান (₹)?','What best describes your occupation?':'আপোনাৰ বৃত্তিৰ কোনটো বৰ্ণনা সৰ্বোত্তম?','Which state do you live in?':'আপুনি কোন ৰাজ্যত বাস কৰে?','What kind of support are you looking for?':'আপুনি কেনেধৰণৰ সহায় বিচাৰিছে?','Your full name':'আপোনাৰ সম্পূৰ্ণ নাম','e.g. 28':'যেনে 28'
  }
};
Object.entries(CHAT_I18N).forEach(([lang, values]) => Object.assign(DICT[lang], values));


// Major page headings/actions used throughout the site.
const UI_I18N = {
hi:{'Official Civic-Tech Portal':'आधिकारिक सिविक-टेक पोर्टल','90 Verified Government Schemes':'90 सत्यापित सरकारी योजनाएँ','Find Government Schemes That Fit You':'अपने लिए उपयुक्त सरकारी योजनाएँ खोजें','Find Matching Schemes':'मिलान वाली योजनाएँ खोजें','Explore All 90 Schemes':'सभी 90 योजनाएँ देखें','Personalized Scheme Matching':'व्यक्तिगत योजना मिलान','Find Government Schemes You May Be Eligible For':'उन सरकारी योजनाओं को खोजें जिनके लिए आप पात्र हो सकते हैं','How CivicLink Works for Citizens':'CivicLink नागरिकों के लिए कैसे काम करता है','Search Schemes by Keyword or Focus Area':'कीवर्ड या क्षेत्र के अनुसार योजनाएँ खोजें','Explore Schemes by Category':'श्रेणी के अनुसार योजनाएँ देखें','View Details':'विवरण देखें','Government Schemes Directory':'सरकारी योजनाओं की सूची','Search':'खोजें','Monthly EMI':'मासिक EMI','Total Interest':'कुल ब्याज','Total Payable':'कुल देय राशि','No results yet':'अभी कोई परिणाम नहीं','Start Smart Matching':'स्मार्ट मिलान शुरू करें','Your Personalized Results':'आपके व्यक्तिगत परिणाम','Print':'प्रिंट','Share':'शेयर','Schemes':'योजनाएँ','Documents':'दस्तावेज़','Action Plan':'कार्य योजना','Verify / CSC':'सत्यापन / CSC','Required Documents Checklist':'आवश्यक दस्तावेज़ चेकलिस्ट','Personalized Action Plan':'व्यक्तिगत कार्य योजना','Verify with CSC / Channel Partner':'CSC / चैनल पार्टनर से सत्यापित करें'},
bn:{'Official Civic-Tech Portal':'অফিশিয়াল সিভিক-টেক পোর্টাল','90 Verified Government Schemes':'৯০টি যাচাইকৃত সরকারি প্রকল্প','Find Government Schemes That Fit You':'আপনার উপযোগী সরকারি প্রকল্প খুঁজুন','Find Matching Schemes':'মিলযুক্ত প্রকল্প খুঁজুন','Explore All 90 Schemes':'সব ৯০টি প্রকল্প দেখুন','Personalized Scheme Matching':'ব্যক্তিগত প্রকল্প ম্যাচিং','Find Government Schemes You May Be Eligible For':'যে সরকারি প্রকল্পগুলির জন্য আপনি যোগ্য হতে পারেন সেগুলি খুঁজুন','How CivicLink Works for Citizens':'নাগরিকদের জন্য CivicLink কীভাবে কাজ করে','Search Schemes by Keyword or Focus Area':'কীওয়ার্ড বা ক্ষেত্র অনুযায়ী প্রকল্প খুঁজুন','Explore Schemes by Category':'বিভাগ অনুযায়ী প্রকল্প দেখুন','View Details':'বিস্তারিত দেখুন','Government Schemes Directory':'সরকারি প্রকল্পের তালিকা','Search':'অনুসন্ধান','Monthly EMI':'মাসিক EMI','Total Interest':'মোট সুদ','Total Payable':'মোট পরিশোধযোগ্য','No results yet':'এখনও কোনো ফল নেই','Start Smart Matching':'স্মার্ট ম্যাচিং শুরু করুন','Your Personalized Results':'আপনার ব্যক্তিগত ফলাফল','Print':'প্রিন্ট','Share':'শেয়ার','Schemes':'প্রকল্প','Documents':'নথি','Action Plan':'করণীয় পরিকল্পনা','Verify / CSC':'যাচাই / CSC','Required Documents Checklist':'প্রয়োজনীয় নথির তালিকা','Personalized Action Plan':'ব্যক্তিগত করণীয় পরিকল্পনা','Verify with CSC / Channel Partner':'CSC / অংশীদারের মাধ্যমে যাচাই করুন'},
ta:{'Official Civic-Tech Portal':'அதிகாரப்பூர்வ Civic-Tech தளம்','90 Verified Government Schemes':'90 சரிபார்க்கப்பட்ட அரசு திட்டங்கள்','Find Government Schemes That Fit You':'உங்களுக்கு ஏற்ற அரசு திட்டங்களைக் கண்டறியுங்கள்','Find Matching Schemes':'பொருந்தும் திட்டங்களைக் கண்டறியுங்கள்','Explore All 90 Schemes':'அனைத்து 90 திட்டங்களையும் பார்க்கவும்','Personalized Scheme Matching':'தனிப்பயன் திட்டப் பொருத்தம்','Find Government Schemes You May Be Eligible For':'நீங்கள் தகுதி பெறக்கூடிய அரசு திட்டங்களைக் கண்டறியுங்கள்','How CivicLink Works for Citizens':'CivicLink குடிமக்களுக்காக எவ்வாறு செயல்படுகிறது','Search Schemes by Keyword or Focus Area':'முக்கிய சொல் அல்லது துறையின்படி திட்டங்களைத் தேடுங்கள்','Explore Schemes by Category':'வகைப்படி திட்டங்களைப் பார்க்கவும்','View Details':'விவரங்களைக் காண்க','Government Schemes Directory':'அரசுத் திட்டங்கள் பட்டியல்','Search':'தேடு','Monthly EMI':'மாத EMI','Total Interest':'மொத்த வட்டி','Total Payable':'மொத்தம் செலுத்த வேண்டியது','No results yet':'இன்னும் முடிவுகள் இல்லை','Start Smart Matching':'ஸ்மார்ட் பொருத்தத்தைத் தொடங்கு','Your Personalized Results':'உங்கள் தனிப்பயன் முடிவுகள்','Print':'அச்சிடு','Share':'பகிர்','Schemes':'திட்டங்கள்','Documents':'ஆவணங்கள்','Action Plan':'செயல் திட்டம்','Verify / CSC':'சரிபார்ப்பு / CSC','Required Documents Checklist':'தேவையான ஆவணப் பட்டியல்','Personalized Action Plan':'தனிப்பயன் செயல் திட்டம்','Verify with CSC / Channel Partner':'CSC / கூட்டாளி மூலம் சரிபார்க்கவும்'},
te:{'Official Civic-Tech Portal':'అధికారిక Civic-Tech పోర్టల్','90 Verified Government Schemes':'90 ధృవీకరించిన ప్రభుత్వ పథకాలు','Find Government Schemes That Fit You':'మీకు సరిపోయే ప్రభుత్వ పథకాలను కనుగొనండి','Find Matching Schemes':'సరిపోలే పథకాలను కనుగొనండి','Explore All 90 Schemes':'అన్ని 90 పథకాలను చూడండి','Personalized Scheme Matching':'వ్యక్తిగత పథక సరిపోలిక','Find Government Schemes You May Be Eligible For':'మీరు అర్హులు కావచ్చే ప్రభుత్వ పథకాలను కనుగొనండి','How CivicLink Works for Citizens':'పౌరుల కోసం CivicLink ఎలా పనిచేస్తుంది','Search Schemes by Keyword or Focus Area':'కీవర్డ్ లేదా రంగం ద్వారా పథకాలను వెతకండి','Explore Schemes by Category':'వర్గం ద్వారా పథకాలను చూడండి','View Details':'వివరాలు చూడండి','Government Schemes Directory':'ప్రభుత్వ పథకాల డైరెక్టరీ','Search':'వెతకండి','Monthly EMI':'నెలవారీ EMI','Total Interest':'మొత్తం వడ్డీ','Total Payable':'చెల్లించాల్సిన మొత్తం','No results yet':'ఇంకా ఫలితాలు లేవు','Start Smart Matching':'స్మార్ట్ మ్యాచ్ ప్రారంభించండి','Your Personalized Results':'మీ వ్యక్తిగత ఫలితాలు','Print':'ముద్రించు','Share':'పంచుకోండి','Schemes':'పథకాలు','Documents':'పత్రాలు','Action Plan':'చర్యా ప్రణాళిక','Verify / CSC':'ధృవీకరణ / CSC','Required Documents Checklist':'అవసరమైన పత్రాల జాబితా','Personalized Action Plan':'వ్యక్తిగత చర్యా ప్రణాళిక','Verify with CSC / Channel Partner':'CSC / భాగస్వామితో ధృవీకరించండి'},
mr:{'Official Civic-Tech Portal':'अधिकृत Civic-Tech पोर्टल','90 Verified Government Schemes':'90 सत्यापित सरकारी योजना','Find Government Schemes That Fit You':'तुमच्यासाठी योग्य सरकारी योजना शोधा','Find Matching Schemes':'जुळणाऱ्या योजना शोधा','Explore All 90 Schemes':'सर्व 90 योजना पहा','Personalized Scheme Matching':'वैयक्तिक योजना जुळणी','Find Government Schemes You May Be Eligible For':'तुम्ही पात्र असू शकता अशा सरकारी योजना शोधा','How CivicLink Works for Citizens':'CivicLink नागरिकांसाठी कसे काम करते','Search Schemes by Keyword or Focus Area':'कीवर्ड किंवा क्षेत्रानुसार योजना शोधा','Explore Schemes by Category':'श्रेणीनुसार योजना पहा','View Details':'तपशील पहा','Government Schemes Directory':'सरकारी योजनांची यादी','Search':'शोधा','Monthly EMI':'मासिक EMI','Total Interest':'एकूण व्याज','Total Payable':'एकूण देय','No results yet':'अजून निकाल नाहीत','Start Smart Matching':'स्मार्ट जुळणी सुरू करा','Your Personalized Results':'तुमचे वैयक्तिक निकाल','Print':'प्रिंट','Share':'शेअर','Schemes':'योजना','Documents':'कागदपत्रे','Action Plan':'कृती योजना','Verify / CSC':'पडताळणी / CSC','Required Documents Checklist':'आवश्यक कागदपत्रांची यादी','Personalized Action Plan':'वैयक्तिक कृती योजना','Verify with CSC / Channel Partner':'CSC / भागीदाराद्वारे पडताळा'},
gu:{'Official Civic-Tech Portal':'સત્તાવાર Civic-Tech પોર્ટલ','90 Verified Government Schemes':'90 ચકાસાયેલ સરકારી યોજનાઓ','Find Government Schemes That Fit You':'તમારા માટે યોગ્ય સરકારી યોજનાઓ શોધો','Find Matching Schemes':'મેળ ખાતી યોજનાઓ શોધો','Explore All 90 Schemes':'તમામ 90 યોજનાઓ જુઓ','Personalized Scheme Matching':'વ્યક્તિગત યોજના મેચિંગ','Find Government Schemes You May Be Eligible For':'તમે પાત્ર હોઈ શકો તેવી સરકારી યોજનાઓ શોધો','How CivicLink Works for Citizens':'નાગરિકો માટે CivicLink કેવી રીતે કાર્ય કરે છે','Search Schemes by Keyword or Focus Area':'કીવર્ડ અથવા ક્ષેત્ર દ્વારા યોજનાઓ શોધો','Explore Schemes by Category':'શ્રેણી પ્રમાણે યોજનાઓ જુઓ','View Details':'વિગતો જુઓ','Government Schemes Directory':'સરકારી યોજનાઓની ડિરેક્ટરી','Search':'શોધો','Monthly EMI':'માસિક EMI','Total Interest':'કુલ વ્યાજ','Total Payable':'કુલ ચૂકવવાપાત્ર','No results yet':'હજુ પરિણામ નથી','Start Smart Matching':'સ્માર્ટ મેચિંગ શરૂ કરો','Your Personalized Results':'તમારા વ્યક્તિગત પરિણામો','Print':'પ્રિન્ટ','Share':'શેર','Schemes':'યોજનાઓ','Documents':'દસ્તાવેજો','Action Plan':'કાર્ય યોજના','Verify / CSC':'ચકાસણી / CSC','Required Documents Checklist':'જરૂરી દસ્તાવેજોની યાદી','Personalized Action Plan':'વ્યક્તિગત કાર્ય યોજના','Verify with CSC / Channel Partner':'CSC / ભાગીદાર દ્વારા ચકાસો'},
kn:{'Official Civic-Tech Portal':'ಅಧಿಕೃತ Civic-Tech ಪೋರ್ಟಲ್','90 Verified Government Schemes':'90 ಪರಿಶೀಲಿತ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು','Find Government Schemes That Fit You':'ನಿಮಗೆ ಸೂಕ್ತವಾದ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ','Find Matching Schemes':'ಹೊಂದುವ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ','Explore All 90 Schemes':'ಎಲ್ಲಾ 90 ಯೋಜನೆಗಳನ್ನು ನೋಡಿ','Personalized Scheme Matching':'ವೈಯಕ್ತಿಕ ಯೋಜನೆ ಹೊಂದಾಣಿಕೆ','Find Government Schemes You May Be Eligible For':'ನೀವು ಅರ್ಹರಾಗಬಹುದಾದ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ','How CivicLink Works for Citizens':'ನಾಗರಿಕರಿಗಾಗಿ CivicLink ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ','Search Schemes by Keyword or Focus Area':'ಕೀವರ್ಡ್ ಅಥವಾ ಕ್ಷೇತ್ರದ ಮೂಲಕ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ','Explore Schemes by Category':'ವರ್ಗದ ಮೂಲಕ ಯೋಜನೆಗಳನ್ನು ನೋಡಿ','View Details':'ವಿವರಗಳನ್ನು ನೋಡಿ','Government Schemes Directory':'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಪಟ್ಟಿ','Search':'ಹುಡುಕಿ','Monthly EMI':'ಮಾಸಿಕ EMI','Total Interest':'ಒಟ್ಟು ಬಡ್ಡಿ','Total Payable':'ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದದ್ದು','No results yet':'ಇನ್ನೂ ಫಲಿತಾಂಶಗಳಿಲ್ಲ','Start Smart Matching':'ಸ್ಮಾರ್ಟ್ ಹೊಂದಾಣಿಕೆ ಪ್ರಾರಂಭಿಸಿ','Your Personalized Results':'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಫಲಿತಾಂಶಗಳು','Print':'ಮುದ್ರಿಸಿ','Share':'ಹಂಚಿಕೊಳ್ಳಿ','Schemes':'ಯೋಜನೆಗಳು','Documents':'ದಾಖಲೆಗಳು','Action Plan':'ಕ್ರಿಯಾ ಯೋಜನೆ','Verify / CSC':'ಪರಿಶೀಲನೆ / CSC','Required Documents Checklist':'ಅಗತ್ಯ ದಾಖಲೆಗಳ ಪಟ್ಟಿ','Personalized Action Plan':'ವೈಯಕ್ತಿಕ ಕ್ರಿಯಾ ಯೋಜನೆ','Verify with CSC / Channel Partner':'CSC / ಪಾಲುದಾರರ ಮೂಲಕ ಪರಿಶೀಲಿಸಿ'},
ml:{'Official Civic-Tech Portal':'ഔദ്യോഗിക Civic-Tech പോർട്ടൽ','90 Verified Government Schemes':'90 പരിശോധിച്ച സർക്കാർ പദ്ധതികൾ','Find Government Schemes That Fit You':'നിങ്ങൾക്ക് അനുയോജ്യമായ സർക്കാർ പദ്ധതികൾ കണ്ടെത്തുക','Find Matching Schemes':'പൊരുത്തപ്പെടുന്ന പദ്ധതികൾ കണ്ടെത്തുക','Explore All 90 Schemes':'എല്ലാ 90 പദ്ധതികളും കാണുക','Personalized Scheme Matching':'വ്യക്തിഗത പദ്ധതി മാച്ചിംഗ്','Find Government Schemes You May Be Eligible For':'നിങ്ങൾക്ക് അർഹതയുണ്ടാകാവുന്ന സർക്കാർ പദ്ധതികൾ കണ്ടെത്തുക','How CivicLink Works for Citizens':'പൗരന്മാർക്കായി CivicLink എങ്ങനെ പ്രവർത്തിക്കുന്നു','Search Schemes by Keyword or Focus Area':'കീവേഡ് അല്ലെങ്കിൽ മേഖല പ്രകാരം പദ്ധതികൾ തിരയുക','Explore Schemes by Category':'വിഭാഗം പ്രകാരം പദ്ധതികൾ കാണുക','View Details':'വിശദാംശങ്ങൾ കാണുക','Government Schemes Directory':'സർക്കാർ പദ്ധതികളുടെ പട്ടിക','Search':'തിരയുക','Monthly EMI':'മാസ EMI','Total Interest':'മൊത്തം പലിശ','Total Payable':'ആകെ അടയ്ക്കേണ്ടത്','No results yet':'ഇതുവരെ ഫലങ്ങളില്ല','Start Smart Matching':'സ്മാർട്ട് മാച്ചിംഗ് ആരംഭിക്കുക','Your Personalized Results':'നിങ്ങളുടെ വ്യക്തിഗത ഫലങ്ങൾ','Print':'പ്രിന്റ്','Share':'പങ്കിടുക','Schemes':'പദ്ധതികൾ','Documents':'രേഖകൾ','Action Plan':'പ്രവർത്തന പദ്ധതി','Verify / CSC':'പരിശോധന / CSC','Required Documents Checklist':'ആവശ്യമായ രേഖകളുടെ പട്ടിക','Personalized Action Plan':'വ്യക്തിഗത പ്രവർത്തന പദ്ധതി','Verify with CSC / Channel Partner':'CSC / പങ്കാളിയിലൂടെ പരിശോധിക്കുക'},
pa:{'Official Civic-Tech Portal':'ਅਧਿਕਾਰਤ Civic-Tech ਪੋਰਟਲ','90 Verified Government Schemes':'90 ਪ੍ਰਮਾਣਿਤ ਸਰਕਾਰੀ ਸਕੀਮਾਂ','Find Government Schemes That Fit You':'ਆਪਣੇ ਲਈ ਢੁਕਵੀਆਂ ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਲੱਭੋ','Find Matching Schemes':'ਮਿਲਦੀਆਂ ਸਕੀਮਾਂ ਲੱਭੋ','Explore All 90 Schemes':'ਸਾਰੀਆਂ 90 ਸਕੀਮਾਂ ਵੇਖੋ','Personalized Scheme Matching':'ਨਿੱਜੀ ਸਕੀਮ ਮੈਚਿੰਗ','Find Government Schemes You May Be Eligible For':'ਉਹ ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਲੱਭੋ ਜਿਨ੍ਹਾਂ ਲਈ ਤੁਸੀਂ ਯੋਗ ਹੋ ਸਕਦੇ ਹੋ','How CivicLink Works for Citizens':'ਨਾਗਰਿਕਾਂ ਲਈ CivicLink ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ','Search Schemes by Keyword or Focus Area':'ਕੀਵਰਡ ਜਾਂ ਖੇਤਰ ਅਨੁਸਾਰ ਸਕੀਮਾਂ ਲੱਭੋ','Explore Schemes by Category':'ਸ਼੍ਰੇਣੀ ਅਨੁਸਾਰ ਸਕੀਮਾਂ ਵੇਖੋ','View Details':'ਵੇਰਵੇ ਵੇਖੋ','Government Schemes Directory':'ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਦੀ ਸੂਚੀ','Search':'ਖੋਜੋ','Monthly EMI':'ਮਹੀਨਾਵਾਰ EMI','Total Interest':'ਕੁੱਲ ਵਿਆਜ','Total Payable':'ਕੁੱਲ ਭੁਗਤਾਨਯੋਗ','No results yet':'ਹਾਲੇ ਕੋਈ ਨਤੀਜੇ ਨਹੀਂ','Start Smart Matching':'ਸਮਾਰਟ ਮੈਚਿੰਗ ਸ਼ੁਰੂ ਕਰੋ','Your Personalized Results':'ਤੁਹਾਡੇ ਨਿੱਜੀ ਨਤੀਜੇ','Print':'ਪ੍ਰਿੰਟ','Share':'ਸਾਂਝਾ ਕਰੋ','Schemes':'ਸਕੀਮਾਂ','Documents':'ਦਸਤਾਵੇਜ਼','Action Plan':'ਕਾਰਵਾਈ ਯੋਜਨਾ','Verify / CSC':'ਤਸਦੀਕ / CSC','Required Documents Checklist':'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼ਾਂ ਦੀ ਸੂਚੀ','Personalized Action Plan':'ਨਿੱਜੀ ਕਾਰਵਾਈ ਯੋਜਨਾ','Verify with CSC / Channel Partner':'CSC / ਭਾਈਵਾਲ ਰਾਹੀਂ ਤਸਦੀਕ ਕਰੋ'},
or:{'Official Civic-Tech Portal':'ଅଧିକାରିକ Civic-Tech ପୋର୍ଟାଲ','90 Verified Government Schemes':'90 ଯାଞ୍ଚିତ ସରକାରୀ ଯୋଜନା','Find Government Schemes That Fit You':'ଆପଣଙ୍କ ପାଇଁ ଉପଯୁକ୍ତ ସରକାରୀ ଯୋଜନା ଖୋଜନ୍ତୁ','Find Matching Schemes':'ମେଳ ଖାଉଥିବା ଯୋଜନା ଖୋଜନ୍ତୁ','Explore All 90 Schemes':'ସମସ୍ତ 90 ଯୋଜନା ଦେଖନ୍ତୁ','Personalized Scheme Matching':'ବ୍ୟକ୍ତିଗତ ଯୋଜନା ମେଳ','Find Government Schemes You May Be Eligible For':'ଆପଣ ଯୋଗ୍ୟ ହୋଇପାରୁଥିବା ସରକାରୀ ଯୋଜନା ଖୋଜନ୍ତୁ','How CivicLink Works for Citizens':'ନାଗରିକଙ୍କ ପାଇଁ CivicLink କିପରି କାମ କରେ','Search Schemes by Keyword or Focus Area':'କୀୱାର୍ଡ କିମ୍ବା କ୍ଷେତ୍ର ଅନୁସାରେ ଯୋଜନା ଖୋଜନ୍ତୁ','Explore Schemes by Category':'ଶ୍ରେଣୀ ଅନୁସାରେ ଯୋଜନା ଦେଖନ୍ତୁ','View Details':'ବିବରଣୀ ଦେଖନ୍ତୁ','Government Schemes Directory':'ସରକାରୀ ଯୋଜନା ତାଲିକା','Search':'ଖୋଜନ୍ତୁ','Monthly EMI':'ମାସିକ EMI','Total Interest':'ମୋଟ ସୁଧ','Total Payable':'ମୋଟ ଦେୟ','No results yet':'ଏପର୍ଯ୍ୟନ୍ତ ଫଳାଫଳ ନାହିଁ','Start Smart Matching':'ସ୍ମାର୍ଟ ମ୍ୟାଚିଂ ଆରମ୍ଭ କରନ୍ତୁ','Your Personalized Results':'ଆପଣଙ୍କ ବ୍ୟକ୍ତିଗତ ଫଳାଫଳ','Print':'ପ୍ରିଣ୍ଟ','Share':'ସେୟାର','Schemes':'ଯୋଜନା','Documents':'ଦଲିଲ','Action Plan':'କାର୍ଯ୍ୟ ଯୋଜନା','Verify / CSC':'ଯାଞ୍ଚ / CSC','Required Documents Checklist':'ଆବଶ୍ୟକ ଦଲିଲ ତାଲିକା','Personalized Action Plan':'ବ୍ୟକ୍ତିଗତ କାର୍ଯ୍ୟ ଯୋଜନା','Verify with CSC / Channel Partner':'CSC / ସହଭାଗୀ ମାଧ୍ୟମରେ ଯାଞ୍ଚ କରନ୍ତୁ'},
as:{'Official Civic-Tech Portal':'অধিকাৰিক Civic-Tech প’ৰ্টেল','90 Verified Government Schemes':'90টা সত্যাপিত চৰকাৰী আঁচনি','Find Government Schemes That Fit You':'আপোনাৰ বাবে উপযুক্ত চৰকাৰী আঁচনি বিচাৰক','Find Matching Schemes':'মিল থকা আঁচনি বিচাৰক','Explore All 90 Schemes':'সকলো 90 আঁচনি চাওক','Personalized Scheme Matching':'ব্যক্তিগত আঁচনি মিল','Find Government Schemes You May Be Eligible For':'আপুনি যোগ্য হ’ব পৰা চৰকাৰী আঁচনি বিচাৰক','How CivicLink Works for Citizens':'নাগৰিকৰ বাবে CivicLink কেনেকৈ কাম কৰে','Search Schemes by Keyword or Focus Area':'কীৱৰ্ড বা ক্ষেত্ৰ অনুসৰি আঁচনি বিচাৰক','Explore Schemes by Category':'শ্ৰেণী অনুসৰি আঁচনি চাওক','View Details':'বিৱৰণ চাওক','Government Schemes Directory':'চৰকাৰী আঁচনিৰ তালিকা','Search':'বিচাৰক','Monthly EMI':'মাহিলী EMI','Total Interest':'মুঠ সুত','Total Payable':'মুঠ পৰিশোধযোগ্য','No results yet':'এতিয়াও কোনো ফলাফল নাই','Start Smart Matching':'স্মাৰ্ট মিল আৰম্ভ কৰক','Your Personalized Results':'আপোনাৰ ব্যক্তিগত ফলাফল','Print':'প্ৰিণ্ট','Share':'শ্বেয়াৰ','Schemes':'আঁচনি','Documents':'নথি','Action Plan':'কাৰ্য পৰিকল্পনা','Verify / CSC':'সত্যাপন / CSC','Required Documents Checklist':'প্ৰয়োজনীয় নথিৰ তালিকা','Personalized Action Plan':'ব্যক্তিগত কাৰ্য পৰিকল্পনা','Verify with CSC / Channel Partner':'CSC / অংশীদাৰৰ জৰিয়তে সত্যাপন কৰক'}
};
Object.entries(UI_I18N).forEach(([lang, values]) => Object.assign(DICT[lang], values));

const LANGUAGE_VOICE = { en:'en-IN', hi:'hi-IN', bn:'bn-IN', ta:'ta-IN', te:'te-IN', mr:'mr-IN', gu:'gu-IN', kn:'kn-IN', ml:'ml-IN', pa:'pa-IN', or:'or-IN', as:'as-IN' };

export const LANG_CODES = Object.fromEntries(LANGUAGES.map(l => [l.code, l.label]));
export const voiceLocale = (code) => LANGUAGE_VOICE[code] || 'en-IN';
export const translate = (code, text) => (DICT[code] && DICT[code][text]) || DICT.en[text] || text;

const LanguageContext = createContext({ language:'en', setLanguage:()=>{}, t:(x)=>x });

export function LanguageProvider({ language, setLanguage, children }) {
  const t = useMemo(() => (text) => translate(language, text), [language]);
  useEffect(() => {
    document.documentElement.lang = language;
    try { localStorage.setItem('civiclink_language', language); } catch(e) {}
  }, [language]);
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
