import React, { createContext, useContext, useEffect, useMemo } from 'react';
import { LANGUAGES } from './mock';

const DICT = {
  en: {
    'GOVT OF INDIA':'GOVT OF INDIA','National Welfare & Credit Guidance Platform':'National Welfare & Credit Guidance Platform',
    'Helpline: 1800-11-2026 (Toll-Free)':'Helpline: 1800-11-2026 (Toll-Free)','Government Citizen Platform':'Government Citizen Platform',
    'Home':'Home','Explore Schemes':'Explore Schemes','Smart Matching':'Smart Matching','Financial Calculator':'Financial Calculator',
    'Find Nearby Partner':'Find Nearby Partner','More':'More','Citizen Login':'Citizen Login','Register':'Register',
    'Official':'Official','Decrease font size':'Decrease font size','Reset font size':'Reset font size','Increase font size':'Increase font size',
    'All Schemes Directory':'All Schemes Directory','Smart Scheme Matching':'Smart Scheme Matching','Loan & Subsidy Calculator':'Loan & Subsidy Calculator',
    'Nearby Partner Centers':'Nearby Partner Centers','Sign In / Portal':'Sign In / Portal','QUICK LINKS':'QUICK LINKS',
    'SUPPORT & HELPLINE':'SUPPORT & HELPLINE','GOVERNANCE & TRUST':'GOVERNANCE & TRUST','Verified':'Verified','Call':'Call','Directions':'Directions',
    'Use My Location':'Use My Location','No partners found for your search.':'No partners found for your search.',
    'Scheme not found':'Scheme not found','Back to Directory':'Back to Directory','Government Verified':'Government Verified',
    'Eligibility Criteria':'Eligibility Criteria','Required Documents':'Required Documents','Ready to Apply?':'Ready to Apply?',
    'Find Partner':'Find Partner','Apply on Portal':'Apply on Portal','Max Support / Loan':'Max Support / Loan','Interest Rate':'Interest Rate',
    'Application Route':'Application Route','Reset':'Reset','CivicLink Assistant':'CivicLink Assistant','Rule-based scheme guidance':'Rule-based scheme guidance',
    'Analyzing your profile against 90 government schemes...':'Analyzing your profile against 90 government schemes...',
    'Type your answer...':'Type your answer...','Voice input':'Voice input','This page does not exist.':'This page does not exist.',
    'Authentication is optional. You can use CivicLink without an account.':'Authentication is optional. You can use CivicLink without an account.',
    'Mobile number':'Mobile number','Password / OTP':'Password / OTP'
  },
  hi: {
    'GOVT OF INDIA':'भारत सरकार','National Welfare & Credit Guidance Platform':'राष्ट्रीय कल्याण एवं ऋण मार्गदर्शन मंच','Helpline: 1800-11-2026 (Toll-Free)':'हेल्पलाइन: 1800-11-2026 (टोल-फ्री)',
    'Government Citizen Platform':'सरकारी नागरिक मंच','Home':'होम','Explore Schemes':'योजनाएँ देखें','Smart Matching':'स्मार्ट मिलान','Financial Calculator':'वित्तीय कैलकुलेटर','Find Nearby Partner':'नज़दीकी साझेदार खोजें','More':'अधिक','Citizen Login':'नागरिक लॉगिन','Register':'पंजीकरण','Official':'आधिकारिक',
    'All Schemes Directory':'सभी योजनाओं की सूची','Smart Scheme Matching':'स्मार्ट योजना मिलान','Loan & Subsidy Calculator':'ऋण एवं सब्सिडी कैलकुलेटर','Nearby Partner Centers':'नज़दीकी साझेदार केंद्र','Sign In / Portal':'साइन इन / पोर्टल','QUICK LINKS':'त्वरित लिंक','SUPPORT & HELPLINE':'सहायता एवं हेल्पलाइन','GOVERNANCE & TRUST':'शासन एवं विश्वास','Verified':'सत्यापित','Call':'कॉल','Directions':'दिशा-निर्देश','Use My Location':'मेरी लोकेशन इस्तेमाल करें','No partners found for your search.':'आपकी खोज के लिए कोई साझेदार नहीं मिला।','Scheme not found':'योजना नहीं मिली','Back to Directory':'सूची पर वापस जाएँ','Government Verified':'सरकार द्वारा सत्यापित','Eligibility Criteria':'पात्रता मानदंड','Required Documents':'आवश्यक दस्तावेज़','Ready to Apply?':'आवेदन के लिए तैयार?','Find Partner':'साझेदार खोजें','Apply on Portal':'पोर्टल पर आवेदन करें','Max Support / Loan':'अधिकतम सहायता / ऋण','Interest Rate':'ब्याज दर','Application Route':'आवेदन का तरीका','Reset':'रीसेट','CivicLink Assistant':'सिविक लिंक सहायक','Rule-based scheme guidance':'नियम-आधारित योजना मार्गदर्शन','Analyzing your profile against 90 government schemes...':'90 सरकारी योजनाओं के अनुसार आपकी प्रोफ़ाइल का विश्लेषण हो रहा है...','Type your answer...':'अपना उत्तर लिखें...','Voice input':'आवाज़ से इनपुट','This page does not exist.':'यह पेज मौजूद नहीं है।','Authentication is optional. You can use CivicLink without an account.':'प्रमाणीकरण वैकल्पिक है। आप बिना खाते के CivicLink का उपयोग कर सकते हैं।','Mobile number':'मोबाइल नंबर','Password / OTP':'पासवर्ड / OTP'
  },
  bn: {'Home':'হোম','Explore Schemes':'প্রকল্প দেখুন','Smart Matching':'স্মার্ট ম্যাচিং','Financial Calculator':'আর্থিক ক্যালকুলেটর','Find Nearby Partner':'কাছের অংশীদার খুঁজুন','More':'আরও','Citizen Login':'নাগরিক লগইন','Register':'নিবন্ধন','Official':'সরকারি','All Schemes Directory':'সব প্রকল্পের তালিকা','Smart Scheme Matching':'স্মার্ট প্রকল্প ম্যাচিং','Loan & Subsidy Calculator':'ঋণ ও ভর্তুকি ক্যালকুলেটর','Verified':'যাচাইকৃত','Call':'কল','Directions':'দিকনির্দেশ','Use My Location':'আমার অবস্থান ব্যবহার করুন','No partners found for your search.':'আপনার অনুসন্ধানে কোনো অংশীদার পাওয়া যায়নি।','Scheme not found':'প্রকল্প পাওয়া যায়নি','Back to Directory':'তালিকায় ফিরুন','Government Verified':'সরকারি যাচাইকৃত','Eligibility Criteria':'যোগ্যতার মানদণ্ড','Required Documents':'প্রয়োজনীয় নথি','Ready to Apply?':'আবেদন করতে প্রস্তুত?','Find Partner':'অংশীদার খুঁজুন','Apply on Portal':'পোর্টালে আবেদন করুন','Max Support / Loan':'সর্বোচ্চ সহায়তা / ঋণ','Interest Rate':'সুদের হার','Application Route':'আবেদনের পদ্ধতি','Reset':'রিসেট','CivicLink Assistant':'CivicLink সহায়ক','Type your answer...':'আপনার উত্তর লিখুন...','Voice input':'ভয়েস ইনপুট','This page does not exist.':'এই পৃষ্ঠাটি নেই।'},
  ta: {'Home':'முகப்பு','Explore Schemes':'திட்டங்களைப் பார்க்க','Smart Matching':'ஸ்மார்ட் பொருத்தம்','Financial Calculator':'நிதி கணிப்பான்','Find Nearby Partner':'அருகிலுள்ள கூட்டாளரைத் தேடு','More':'மேலும்','Citizen Login':'குடிமக்கள் உள்நுழைவு','Register':'பதிவு','Official':'அதிகாரப்பூர்வ','All Schemes Directory':'அனைத்து திட்டங்கள்','Verified':'சரிபார்க்கப்பட்டது','Call':'அழைப்பு','Directions':'வழிகள்','Use My Location':'என் இருப்பிடத்தைப் பயன்படுத்து','Scheme not found':'திட்டம் கிடைக்கவில்லை','Back to Directory':'பட்டியலுக்குத் திரும்பு','Government Verified':'அரசால் சரிபார்க்கப்பட்டது','Eligibility Criteria':'தகுதி அளவுகோல்கள்','Required Documents':'தேவையான ஆவணங்கள்','Ready to Apply?':'விண்ணப்பிக்கத் தயாரா?','Find Partner':'கூட்டாளரைக் கண்டுபிடி','Apply on Portal':'போர்டலில் விண்ணப்பி','Max Support / Loan':'அதிகபட்ச உதவி / கடன்','Interest Rate':'வட்டி விகிதம்','Application Route':'விண்ணப்ப முறை','Reset':'மீட்டமை','CivicLink Assistant':'CivicLink உதவியாளர்','Type your answer...':'உங்கள் பதிலை உள்ளிடவும்...','Voice input':'குரல் உள்ளீடு','This page does not exist.':'இந்தப் பக்கம் இல்லை.'},
  te: {'Home':'హోమ్','Explore Schemes':'పథకాలను చూడండి','Smart Matching':'స్మార్ట్ మ్యాచ్','Financial Calculator':'ఆర్థిక కాలిక్యులేటర్','Find Nearby Partner':'సమీప భాగస్వామిని కనుగొనండి','More':'మరిన్ని','Citizen Login':'పౌర లాగిన్','Register':'నమోదు','Official':'అధికారిక','All Schemes Directory':'అన్ని పథకాల జాబితా','Verified':'ధృవీకరించబడింది','Call':'కాల్','Directions':'దిశలు','Use My Location':'నా స్థానాన్ని ఉపయోగించండి','Scheme not found':'పథకం కనబడలేదు','Back to Directory':'జాబితాకు తిరిగి వెళ్లండి','Government Verified':'ప్రభుత్వ ధృవీకరణ','Eligibility Criteria':'అర్హత ప్రమాణాలు','Required Documents':'అవసరమైన పత్రాలు','Ready to Apply?':'దరఖాస్తు చేయడానికి సిద్ధంగా ఉన్నారా?','Find Partner':'భాగస్వామిని కనుగొనండి','Apply on Portal':'పోర్టల్‌లో దరఖాస్తు చేయండి','Max Support / Loan':'గరిష్ఠ సహాయం / రుణం','Interest Rate':'వడ్డీ రేటు','Application Route':'దరఖాస్తు విధానం','Reset':'రీసెట్','CivicLink Assistant':'CivicLink సహాయకుడు','Type your answer...':'మీ సమాధానాన్ని టైప్ చేయండి...','Voice input':'వాయిస్ ఇన్‌పుట్','This page does not exist.':'ఈ పేజీ లేదు.'},
  mr: {'Home':'मुख्यपृष्ठ','Explore Schemes':'योजना पहा','Smart Matching':'स्मार्ट जुळणी','Financial Calculator':'आर्थिक कॅल्क्युलेटर','Find Nearby Partner':'जवळचा भागीदार शोधा','More':'अधिक','Citizen Login':'नागरिक लॉगिन','Register':'नोंदणी','Official':'अधिकृत','All Schemes Directory':'सर्व योजनांची यादी','Verified':'सत्यापित','Call':'कॉल','Directions':'दिशा','Use My Location':'माझे स्थान वापरा','Scheme not found':'योजना सापडली नाही','Back to Directory':'यादीकडे परत जा','Government Verified':'सरकारद्वारे सत्यापित','Eligibility Criteria':'पात्रता निकष','Required Documents':'आवश्यक कागदपत्रे','Ready to Apply?':'अर्ज करण्यास तयार आहात?','Find Partner':'भागीदार शोधा','Apply on Portal':'पोर्टलवर अर्ज करा','Max Support / Loan':'कमाल मदत / कर्ज','Interest Rate':'व्याजदर','Application Route':'अर्ज पद्धत','Reset':'रीसेट','CivicLink Assistant':'CivicLink सहाय्यक','Type your answer...':'तुमचे उत्तर टाइप करा...','Voice input':'व्हॉइस इनपुट','This page does not exist.':'हे पृष्ठ अस्तित्वात नाही.'},
  gu: {'Home':'હોમ','Explore Schemes':'યોજનાઓ જુઓ','Smart Matching':'સ્માર્ટ મેચિંગ','Financial Calculator':'નાણાકીય કેલ્ક્યુલેટર','Find Nearby Partner':'નજીકનો ભાગીદાર શોધો','More':'વધુ','Citizen Login':'નાગરિક લૉગિન','Register':'નોંધણી','Official':'સત્તાવાર','All Schemes Directory':'તમામ યોજનાઓની યાદી','Verified':'ચકાસાયેલ','Call':'કૉલ','Directions':'દિશા-નિર્દેશ','Use My Location':'મારું સ્થાન વાપરો','Scheme not found':'યોજના મળી નથી','Back to Directory':'યાદી પર પાછા જાઓ','Government Verified':'સરકાર દ્વારા ચકાસાયેલ','Eligibility Criteria':'પાત્રતા માપદંડ','Required Documents':'જરૂરી દસ્તાવેજો','Ready to Apply?':'અરજી કરવા તૈયાર છો?','Find Partner':'ભાગીદાર શોધો','Apply on Portal':'પોર્ટલ પર અરજી કરો','Max Support / Loan':'મહત્તમ સહાય / લોન','Interest Rate':'વ્યાજ દર','Application Route':'અરજીનો માર્ગ','Reset':'રીસેટ','CivicLink Assistant':'CivicLink સહાયક','Type your answer...':'તમારો જવાબ લખો...','Voice input':'વૉઇસ ઇનપુટ','This page does not exist.':'આ પૃષ્ઠ અસ્તિત્વમાં નથી.'},
  kn: {'Home':'ಮುಖಪುಟ','Explore Schemes':'ಯೋಜನೆಗಳನ್ನು ನೋಡಿ','Smart Matching':'ಸ್ಮಾರ್ಟ್ ಹೊಂದಾಣಿಕೆ','Financial Calculator':'ಹಣಕಾಸು ಕ್ಯಾಲ್ಕುಲೇಟರ್','Find Nearby Partner':'ಹತ್ತಿರದ ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ','More':'ಇನ್ನಷ್ಟು','Citizen Login':'ನಾಗರಿಕ ಲಾಗಿನ್','Register':'ನೋಂದಣಿ','Official':'ಅಧಿಕೃತ','All Schemes Directory':'ಎಲ್ಲಾ ಯೋಜನೆಗಳ ಪಟ್ಟಿ','Verified':'ಪರಿಶೀಲಿಸಲಾಗಿದೆ','Call':'ಕರೆ','Directions':'ದಿಕ್ಕುಗಳು','Use My Location':'ನನ್ನ ಸ್ಥಳ ಬಳಸಿ','Scheme not found':'ಯೋಜನೆ ಕಂಡುಬಂದಿಲ್ಲ','Back to Directory':'ಪಟ್ಟಿಗೆ ಹಿಂತಿರುಗಿ','Government Verified':'ಸರ್ಕಾರದಿಂದ ಪರಿಶೀಲಿಸಲಾಗಿದೆ','Eligibility Criteria':'ಅರ್ಹತಾ ಮಾನದಂಡಗಳು','Required Documents':'ಅಗತ್ಯ ದಾಖಲೆಗಳು','Ready to Apply?':'ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಸಿದ್ಧವೇ?','Find Partner':'ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ','Apply on Portal':'ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ','Max Support / Loan':'ಗರಿಷ್ಠ ಸಹಾಯ / ಸಾಲ','Interest Rate':'ಬಡ್ಡಿ ದರ','Application Route':'ಅರ್ಜಿ ವಿಧಾನ','Reset':'ಮರುಹೊಂದಿಸಿ','CivicLink Assistant':'CivicLink ಸಹಾಯಕ','Type your answer...':'ನಿಮ್ಮ ಉತ್ತರವನ್ನು ಟೈಪ್ ಮಾಡಿ...','Voice input':'ಧ್ವನಿ ಇನ್‌ಪುಟ್','This page does not exist.':'ಈ ಪುಟ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ.'},
  ml: {'Home':'ഹോം','Explore Schemes':'പദ്ധതികൾ കാണുക','Smart Matching':'സ്മാർട്ട് മാച്ചിംഗ്','Financial Calculator':'സാമ്പത്തിക കാൽക്കുലേറ്റർ','Find Nearby Partner':'അടുത്തുള്ള പങ്കാളിയെ കണ്ടെത്തുക','More':'കൂടുതൽ','Citizen Login':'പൗര ലോഗിൻ','Register':'രജിസ്റ്റർ','Official':'ഔദ്യോഗിക','All Schemes Directory':'എല്ലാ പദ്ധതികളുടെയും പട്ടിക','Verified':'പരിശോധിച്ചത്','Call':'വിളിക്കുക','Directions':'ദിശകൾ','Use My Location':'എന്റെ സ്ഥലം ഉപയോഗിക്കുക','Scheme not found':'പദ്ധതി കണ്ടെത്തിയില്ല','Back to Directory':'പട്ടികയിലേക്ക് മടങ്ങുക','Government Verified':'സർക്കാർ പരിശോധിച്ചത്','Eligibility Criteria':'യോഗ്യതാ മാനദണ്ഡങ്ങൾ','Required Documents':'ആവശ്യമായ രേഖകൾ','Ready to Apply?':'അപേക്ഷിക്കാൻ തയ്യാറാണോ?','Find Partner':'പങ്കാളിയെ കണ്ടെത്തുക','Apply on Portal':'പോർട്ടലിൽ അപേക്ഷിക്കുക','Max Support / Loan':'പരമാവധി സഹായം / വായ്പ','Interest Rate':'പലിശ നിരക്ക്','Application Route':'അപേക്ഷാ മാർഗം','Reset':'റീസെറ്റ്','CivicLink Assistant':'CivicLink സഹായി','Type your answer...':'നിങ്ങളുടെ ഉത്തരം ടൈപ്പ് ചെയ്യുക...','Voice input':'വോയ്സ് ഇൻപുട്ട്','This page does not exist.':'ഈ പേജ് നിലവിലില്ല.'},
  pa: {'Home':'ਹੋਮ','Explore Schemes':'ਸਕੀਮਾਂ ਵੇਖੋ','Smart Matching':'ਸਮਾਰਟ ਮੈਚਿੰਗ','Financial Calculator':'ਵਿੱਤੀ ਕੈਲਕੁਲੇਟਰ','Find Nearby Partner':'ਨੇੜਲਾ ਭਾਈਵਾਲ ਲੱਭੋ','More':'ਹੋਰ','Citizen Login':'ਨਾਗਰਿਕ ਲੌਗਇਨ','Register':'ਰਜਿਸਟਰ','Official':'ਅਧਿਕਾਰਤ','All Schemes Directory':'ਸਾਰੀਆਂ ਸਕੀਮਾਂ ਦੀ ਸੂਚੀ','Verified':'ਪ੍ਰਮਾਣਿਤ','Call':'ਕਾਲ','Directions':'ਦਿਸ਼ਾਵਾਂ','Use My Location':'ਮੇਰੀ ਸਥਿਤੀ ਵਰਤੋ','Scheme not found':'ਸਕੀਮ ਨਹੀਂ ਮਿਲੀ','Back to Directory':'ਸੂਚੀ ਤੇ ਵਾਪਸ ਜਾਓ','Government Verified':'ਸਰਕਾਰ ਵੱਲੋਂ ਪ੍ਰਮਾਣਿਤ','Eligibility Criteria':'ਯੋਗਤਾ ਮਾਪਦੰਡ','Required Documents':'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼','Ready to Apply?':'ਅਰਜ਼ੀ ਲਈ ਤਿਆਰ ਹੋ?','Find Partner':'ਭਾਈਵਾਲ ਲੱਭੋ','Apply on Portal':'ਪੋਰਟਲ ਤੇ ਅਰਜ਼ੀ ਦਿਓ','Max Support / Loan':'ਵੱਧ ਤੋਂ ਵੱਧ ਸਹਾਇਤਾ / ਕਰਜ਼ਾ','Interest Rate':'ਵਿਆਜ ਦਰ','Application Route':'ਅਰਜ਼ੀ ਦਾ ਰਸਤਾ','Reset':'ਰੀਸੈੱਟ','CivicLink Assistant':'CivicLink ਸਹਾਇਕ','Type your answer...':'ਆਪਣਾ ਜਵਾਬ ਲਿਖੋ...','Voice input':'ਆਵਾਜ਼ ਇਨਪੁੱਟ','This page does not exist.':'ਇਹ ਪੰਨਾ ਮੌਜੂਦ ਨਹੀਂ ਹੈ.'},
  or: {'Home':'ମୁଖ୍ୟ ପୃଷ୍ଠା','Explore Schemes':'ଯୋଜନା ଦେଖନ୍ତୁ','Smart Matching':'ସ୍ମାର୍ଟ ମ୍ୟାଚିଂ','Financial Calculator':'ଆର୍ଥିକ କ୍ୟାଲକୁଲେଟର','Find Nearby Partner':'ନିକଟସ୍ଥ ସହଭାଗୀ ଖୋଜନ୍ତୁ','More':'ଅଧିକ','Citizen Login':'ନାଗରିକ ଲଗଇନ','Register':'ପଞ୍ଜୀକରଣ','Official':'ସରକାରୀ','All Schemes Directory':'ସମସ୍ତ ଯୋଜନା ତାଲିକା','Verified':'ଯାଞ୍ଚିତ','Call':'କଲ୍','Directions':'ଦିଗନିର୍ଦ୍ଦେଶ','Use My Location':'ମୋ ଅବସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ','Scheme not found':'ଯୋଜନା ମିଳିଲା ନାହିଁ','Back to Directory':'ତାଲିକାକୁ ଫେରନ୍ତୁ','Government Verified':'ସରକାରୀ ଯାଞ୍ଚିତ','Eligibility Criteria':'ଯୋଗ୍ୟତା ମାନଦଣ୍ଡ','Required Documents':'ଆବଶ୍ୟକ ଦଲିଲ','Ready to Apply?':'ଆବେଦନ ପାଇଁ ପ୍ରସ୍ତୁତ?','Find Partner':'ସହଭାଗୀ ଖୋଜନ୍ତୁ','Apply on Portal':'ପୋର୍ଟାଲରେ ଆବେଦନ କରନ୍ତୁ','Max Support / Loan':'ସର୍ବାଧିକ ସହାୟତା / ଋଣ','Interest Rate':'ସୁଧ ହାର','Application Route':'ଆବେଦନ ପଦ୍ଧତି','Reset':'ରିସେଟ୍','CivicLink Assistant':'CivicLink ସହାୟକ','Type your answer...':'ଆପଣଙ୍କ ଉତ୍ତର ଲେଖନ୍ତୁ...','Voice input':'ଭଏସ୍ ଇନପୁଟ୍','This page does not exist.':'ଏହି ପୃଷ୍ଠା ନାହିଁ.'},
  as: {'Home':'হোম','Explore Schemes':'আঁচনিসমূহ চাওক','Smart Matching':'স্মাৰ্ট মিল','Financial Calculator':'বিত্তীয় কেলকুলেটৰ','Find Nearby Partner':'ওচৰৰ অংশীদাৰ বিচাৰক','More':'অধিক','Citizen Login':'নাগৰিক লগইন','Register':'পঞ্জীয়ন','Official':'চৰকাৰী','All Schemes Directory':'সকলো আঁচনিৰ তালিকা','Verified':'সত্যাপিত','Call':'কল','Directions':'দিশ-নিৰ্দেশ','Use My Location':'মোৰ অৱস্থান ব্যৱহাৰ কৰক','Scheme not found':'আঁচনি পোৱা নগল','Back to Directory':'তালিকালৈ উভতি যাওক','Government Verified':'চৰকাৰীভাৱে সত্যাপিত','Eligibility Criteria':'যোগ্যতাৰ মাপকাঠী','Required Documents':'প্ৰয়োজনীয় নথি','Ready to Apply?':'আবেদন কৰিবলৈ সাজু?','Find Partner':'অংশীদাৰ বিচাৰক','Apply on Portal':'পৰ্টেলত আবেদন কৰক','Max Support / Loan':'সৰ্বাধিক সহায় / ঋণ','Interest Rate':'সুতৰ হাৰ','Application Route':'আবেদনৰ পদ্ধতি','Reset':'ৰিছেট','CivicLink Assistant':'CivicLink সহায়ক','Type your answer...':'আপোনাৰ উত্তৰ লিখক...','Voice input':'ভইচ ইনপুট','This page does not exist.':'এই পৃষ্ঠা নাই.'}
};


// Conversational assistant localization. Keys stay in English so profile values sent to the backend remain canonical.
const CHAT_I18N = {
  hi: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'नमस्ते! मैं CivicLink सहायक हूँ। क्या मैं आपका नाम जान सकता हूँ?','Thank you. What is your age in years?':'धन्यवाद। आपकी आयु कितने वर्ष है?','Please share your gender.':'कृपया अपना लिंग बताएं।','Which social category do you belong to?':'आप किस सामाजिक श्रेणी से संबंधित हैं?','What is your approximate annual family income (₹)?':'आपकी अनुमानित वार्षिक पारिवारिक आय कितनी है (₹)?','What best describes your occupation?':'आपके व्यवसाय का सबसे सही वर्णन क्या है?','Which state do you live in?':'आप किस राज्य में रहते हैं?','What kind of support are you looking for?':'आप किस प्रकार की सहायता चाहते हैं?','Your full name':'अपना पूरा नाम','e.g. 28':'जैसे 28'
  },
  bn: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'নমস্কার! আমি CivicLink সহায়ক। আপনার নাম জানতে পারি?','Thank you. What is your age in years?':'ধন্যবাদ। আপনার বয়স কত বছর?','Please share your gender.':'অনুগ্রহ করে আপনার লিঙ্গ জানান।','Which social category do you belong to?':'আপনি কোন সামাজিক শ্রেণির অন্তর্ভুক্ত?','What is your approximate annual family income (₹)?':'আপনার আনুমানিক বার্ষিক পারিবারিক আয় কত (₹)?','What best describes your occupation?':'আপনার পেশাকে সবচেয়ে ভালোভাবে কী বর্ণনা করে?','Which state do you live in?':'আপনি কোন রাজ্যে থাকেন?','What kind of support are you looking for?':'আপনি কী ধরনের সহায়তা চান?','Your full name':'আপনার পুরো নাম','e.g. 28':'যেমন ২৮'
  },
  ta: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'வணக்கம்! நான் CivicLink உதவியாளர். உங்கள் பெயரை அறியலாமா?','Thank you. What is your age in years?':'நன்றி. உங்கள் வயது எத்தனை ஆண்டுகள்?','Please share your gender.':'உங்கள் பாலினத்தைப் பகிரவும்.','Which social category do you belong to?':'நீங்கள் எந்த சமூகப் பிரிவைச் சேர்ந்தவர்?','What is your approximate annual family income (₹)?':'உங்கள் குடும்பத்தின் தோராயமான ஆண்டு வருமானம் என்ன (₹)?','What best describes your occupation?':'உங்கள் தொழிலை எது சிறப்பாக விவரிக்கிறது?','Which state do you live in?':'நீங்கள் எந்த மாநிலத்தில் வசிக்கிறீர்கள்?','What kind of support are you looking for?':'நீங்கள் எந்த வகையான உதவியைத் தேடுகிறீர்கள்?','Your full name':'உங்கள் முழுப் பெயர்','e.g. 28':'எ.கா. 28'
  },
  te: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'నమస్తే! నేను CivicLink సహాయకుడిని. మీ పేరు తెలుసుకోవచ్చా?','Thank you. What is your age in years?':'ధన్యవాదాలు. మీ వయస్సు ఎంత?','Please share your gender.':'దయచేసి మీ లింగాన్ని తెలియజేయండి.','Which social category do you belong to?':'మీరు ఏ సామాజిక వర్గానికి చెందుతారు?','What is your approximate annual family income (₹)?':'మీ కుటుంబ వార్షిక ఆదాయం సుమారుగా ఎంత (₹)?','What best describes your occupation?':'మీ వృత్తిని ఏది ఉత్తమంగా వివరిస్తుంది?','Which state do you live in?':'మీరు ఏ రాష్ట్రంలో నివసిస్తున్నారు?','What kind of support are you looking for?':'మీరు ఎలాంటి సహాయం కోరుతున్నారు?','Your full name':'మీ పూర్తి పేరు','e.g. 28':'ఉదా. 28'
  },
  mr: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'नमस्कार! मी CivicLink सहाय्यक आहे. तुमचे नाव सांगाल का?','Thank you. What is your age in years?':'धन्यवाद. तुमचे वय किती वर्षे आहे?','Please share your gender.':'कृपया तुमचे लिंग सांगा.','Which social category do you belong to?':'तुम्ही कोणत्या सामाजिक श्रेणीतील आहात?','What is your approximate annual family income (₹)?':'तुमचे अंदाजे वार्षिक कौटुंबिक उत्पन्न किती आहे (₹)?','What best describes your occupation?':'तुमच्या व्यवसायाचे सर्वात योग्य वर्णन कोणते?','Which state do you live in?':'तुम्ही कोणत्या राज्यात राहता?','What kind of support are you looking for?':'तुम्ही कोणत्या प्रकारची मदत शोधत आहात?','Your full name':'तुमचे पूर्ण नाव','e.g. 28':'उदा. 28'
  },
  gu: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'નમસ્તે! હું CivicLink સહાયક છું. શું હું તમારું નામ જાણી શકું?','Thank you. What is your age in years?':'આભાર. તમારી ઉંમર કેટલી છે?','Please share your gender.':'કૃપા કરીને તમારું લિંગ જણાવો.','Which social category do you belong to?':'તમે કઈ સામાજિક શ્રેણી સાથે સંબંધિત છો?','What is your approximate annual family income (₹)?':'તમારી અંદાજિત વાર્ષિક કૌટુંબિક આવક કેટલી છે (₹)?','What best describes your occupation?':'તમારા વ્યવસાયનું સૌથી યોગ્ય વર્ણન શું છે?','Which state do you live in?':'તમે કયા રાજ્યમાં રહો છો?','What kind of support are you looking for?':'તમે કયા પ્રકારની સહાય શોધી રહ્યા છો?','Your full name':'તમારું પૂરું નામ','e.g. 28':'જેમ કે 28'
  },
  kn: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'ನಮಸ್ಕಾರ! ನಾನು CivicLink ಸಹಾಯಕ. ನಿಮ್ಮ ಹೆಸರು ತಿಳಿಸಬಹುದೇ?','Thank you. What is your age in years?':'ಧನ್ಯವಾದಗಳು. ನಿಮ್ಮ ವಯಸ್ಸು ಎಷ್ಟು?','Please share your gender.':'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಲಿಂಗವನ್ನು ತಿಳಿಸಿ.','Which social category do you belong to?':'ನೀವು ಯಾವ ಸಾಮಾಜಿಕ ವರ್ಗಕ್ಕೆ ಸೇರಿದವರು?','What is your approximate annual family income (₹)?':'ನಿಮ್ಮ ಅಂದಾಜು ವಾರ್ಷಿಕ ಕುಟುಂಬ ಆದಾಯ ಎಷ್ಟು (₹)?','What best describes your occupation?':'ನಿಮ್ಮ ಉದ್ಯೋಗವನ್ನು ಯಾವುದು ಉತ್ತಮವಾಗಿ ವಿವರಿಸುತ್ತದೆ?','Which state do you live in?':'ನೀವು ಯಾವ ರಾಜ್ಯದಲ್ಲಿ ವಾಸಿಸುತ್ತೀರಿ?','What kind of support are you looking for?':'ನೀವು ಯಾವ ರೀತಿಯ ಸಹಾಯವನ್ನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ?','Your full name':'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು','e.g. 28':'ಉದಾ. 28'
  },
  ml: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'നമസ്കാരം! ഞാൻ CivicLink സഹായി. നിങ്ങളുടെ പേര് അറിയാമോ?','Thank you. What is your age in years?':'നന്ദി. നിങ്ങളുടെ പ്രായം എത്രയാണ്?','Please share your gender.':'ദയവായി നിങ്ങളുടെ ലിംഗം അറിയിക്കുക.','Which social category do you belong to?':'നിങ്ങൾ ഏത് സാമൂഹിക വിഭാഗത്തിൽപ്പെടുന്നു?','What is your approximate annual family income (₹)?':'നിങ്ങളുടെ ഏകദേശ വാർഷിക കുടുംബവരുമാനം എത്രയാണ് (₹)?','What best describes your occupation?':'നിങ്ങളുടെ തൊഴിൽ ഏതാണ് ഏറ്റവും നന്നായി വിവരിക്കുന്നത്?','Which state do you live in?':'നിങ്ങൾ ഏത് സംസ്ഥാനത്താണ് താമസിക്കുന്നത്?','What kind of support are you looking for?':'നിങ്ങൾ ഏത് തരത്തിലുള്ള സഹായമാണ് തേടുന്നത്?','Your full name':'നിങ്ങളുടെ പൂർണ്ണ പേര്','e.g. 28':'ഉദാ. 28'
  },
  pa: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ CivicLink ਸਹਾਇਕ ਹਾਂ। ਕੀ ਮੈਂ ਤੁਹਾਡਾ ਨਾਮ ਜਾਣ ਸਕਦਾ ਹਾਂ?','Thank you. What is your age in years?':'ਧੰਨਵਾਦ। ਤੁਹਾਡੀ ਉਮਰ ਕਿੰਨੀ ਹੈ?','Please share your gender.':'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਲਿੰਗ ਦੱਸੋ।','Which social category do you belong to?':'ਤੁਸੀਂ ਕਿਸ ਸਮਾਜਿਕ ਸ਼੍ਰੇਣੀ ਨਾਲ ਸਬੰਧਤ ਹੋ?','What is your approximate annual family income (₹)?':'ਤੁਹਾਡੀ ਲਗਭਗ ਸਾਲਾਨਾ ਪਰਿਵਾਰਕ ਆਮਦਨ ਕਿੰਨੀ ਹੈ (₹)?','What best describes your occupation?':'ਤੁਹਾਡੇ ਕਿੱਤੇ ਦਾ ਸਭ ਤੋਂ ਵਧੀਆ ਵਰਣਨ ਕੀ ਹੈ?','Which state do you live in?':'ਤੁਸੀਂ ਕਿਸ ਰਾਜ ਵਿੱਚ ਰਹਿੰਦੇ ਹੋ?','What kind of support are you looking for?':'ਤੁਸੀਂ ਕਿਸ ਕਿਸਮ ਦੀ ਸਹਾਇਤਾ ਚਾਹੁੰਦੇ ਹੋ?','Your full name':'ਤੁਹਾਡਾ ਪੂਰਾ ਨਾਮ','e.g. 28':'ਜਿਵੇਂ 28'
  },
  or: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'ନମସ୍କାର! ମୁଁ CivicLink ସହାୟକ। ଆପଣଙ୍କ ନାମ ଜାଣିପାରିବି କି?','Thank you. What is your age in years?':'ଧନ୍ୟବାଦ। ଆପଣଙ୍କ ବୟସ କେତେ?','Please share your gender.':'ଦୟାକରି ଆପଣଙ୍କ ଲିଙ୍ଗ କୁହନ୍ତୁ।','Which social category do you belong to?':'ଆପଣ କେଉଁ ସାମାଜିକ ବର୍ଗର?','What is your approximate annual family income (₹)?':'ଆପଣଙ୍କ ଆନୁମାନିକ ବାର୍ଷିକ ପରିବାର ଆୟ କେତେ (₹)?','What best describes your occupation?':'ଆପଣଙ୍କ ବୃତ୍ତିକୁ କେଉଁଟି ଭଲଭାବେ ବର୍ଣ୍ଣନା କରେ?','Which state do you live in?':'ଆପଣ କେଉଁ ରାଜ୍ୟରେ ରହୁଛନ୍ତି?','What kind of support are you looking for?':'ଆପଣ କେଉଁ ପ୍ରକାର ସହାୟତା ଚାହୁଁଛନ୍ତି?','Your full name':'ଆପଣଙ୍କ ସମ୍ପୂର୍ଣ୍ଣ ନାମ','e.g. 28':'ଯଥା 28'
  },
  as: {
    'Namaste! I am the CivicLink Assistant. May I know your name?':'নমস্কাৰ! মই CivicLink সহায়ক। আপোনাৰ নাম জানিব পাৰোঁনে?','Thank you. What is your age in years?':'ধন্যবাদ। আপোনাৰ বয়স কিমান বছৰ?','Please share your gender.':'অনুগ্ৰহ কৰি আপোনাৰ লিংগ জনাওক।','Which social category do you belong to?':'আপুনি কোন সামাজিক শ্ৰেণীৰ অন্তৰ্গত?','What is your approximate annual family income (₹)?':'আপোনাৰ আনুমানিক বাৰ্ষিক পৰিয়ালৰ আয় কিমান (₹)?','What best describes your occupation?':'আপোনাৰ বৃত্তিৰ কোনটো বৰ্ণনা সৰ্বোত্তম?','Which state do you live in?':'আপুনি কোন ৰাজ্যত বাস কৰে?','What kind of support are you looking for?':'আপুনি কেনেধৰণৰ সহায় বিচাৰিছে?','Your full name':'আপোনাৰ সম্পূৰ্ণ নাম','e.g. 28':'যেনে 28'
  }
};
Object.entries(CHAT_I18N).forEach(([lang, values]) => Object.assign(DICT[lang], values));

const LANGUAGE_VOICE = { en:'en-IN', hi:'hi-IN', bn:'bn-IN', ta:'ta-IN', te:'te-IN', mr:'mr-IN', gu:'gu-IN', kn:'kn-IN', ml:'ml-IN', pa:'pa-IN', or:'or-IN', as:'as-IN' };

export const LANG_CODES = Object.fromEntries(LANGUAGES.map(l => [l.code, l.label]));
export const voiceLocale = (code) => LANGUAGE_VOICE[code] || 'en-IN';
export const translate = (code, text) => (DICT[code] && DICT[code][text]) || DICT.en[text] || text;

const LanguageContext = createContext({ language:'en', setLanguage:()=>{}, t:(x)=>x });

export function LanguageProvider({ language, setLanguage, children }) {
  const t = useMemo(() => (text) => translate(language, text), [language]);
  useEffect(() => {
    document.documentElement.lang = language;
    try { localStorage.setItem('civiclink_language', language); } catch(e) {}
  }, [language]);
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
