// Mock data for CivicLink

export const CATEGORIES = [
  {
    id: 'msme',
    name: 'MSME & Business Credit',
    description: 'Collateral-free business loans, working capital & capital subsidies for micro enterprises.',
    tag: 'PMEGP, MUDRA, Stand-Up India',
    icon: 'Briefcase',
    color: 'from-orange-500 to-amber-500',
  },
  {
    id: 'agri',
    name: 'Agriculture & Rural Enterprise',
    description: 'Kisan credit loans, livestock capital subsidies & rural enterprise development grants.',
    tag: 'KCC, NLM, PM-KUSUM',
    icon: 'Sprout',
    color: 'from-emerald-500 to-green-500',
  },
  {
    id: 'artisan',
    name: 'Artisans & Traditional Trades',
    description: 'Collateral-free credit, toolkits & skill upgradation for 18 traditional craftsmanship trades.',
    tag: 'PM Vishwakarma, NSFDC',
    icon: 'Hammer',
    color: 'from-rose-500 to-pink-500',
  },
  {
    id: 'edu',
    name: 'Education & Scholarships',
    description: 'Pre-matric, post-matric and top-class education financial assistance for deserving students.',
    tag: 'PM-YASASVI, NMMS',
    icon: 'GraduationCap',
    color: 'from-sky-500 to-blue-500',
  },
  {
    id: 'social',
    name: 'Social Security & Pensions',
    description: 'Guaranteed monthly pensions, accident insurance & term life protection for workers.',
    tag: 'APY, PMSBY, PMJJBY',
    icon: 'ShieldCheck',
    color: 'from-violet-500 to-purple-500',
  },
  {
    id: 'health',
    name: 'Health & Family Welfare',
    description: '\u20B95 Lakh cashless health cover, maternal benefits & specialized child welfare schemes.',
    tag: 'AB-PMJAY, PMMVY, SSY',
    icon: 'HeartPulse',
    color: 'from-red-500 to-rose-500',
  },
];

export const FOCUS_TAGS = [
  'MUDRA Loan',
  'Women Entrepreneurs',
  'PM Vishwakarma',
  'Agriculture & Dairy',
  'Scholarships',
  'Ayushman Bharat',
];

export const MINISTRIES = [
  'Ministry of Finance',
  'Ministry of Micro, Small and Medium Enterprises',
  'Ministry of Agriculture & Farmers Welfare',
  'Ministry of Rural Development',
  'Ministry of Social Justice and Empowerment',
  'Ministry of Health and Family Welfare',
  'Ministry of Women and Child Development',
  'Ministry of Skill Development and Entrepreneurship',
  'Ministry of Education',
  'Ministry of Housing and Urban Affairs',
  'Ministry of Textiles',
  'Ministry of Labour and Employment',
];

export const SECTORS = [
  'Credit / Loan',
  'Insurance',
  'Pension',
  'Subsidy',
  'Skill Development',
  'Health',
  'Education',
  'Agriculture',
  'Housing',
  'Employment',
];

export const BENEFICIARIES = [
  'General Citizen',
  'Women',
  'Farmers',
  'Students',
  'Senior Citizens',
  'SC / ST',
  'OBC',
  'Minorities',
  'Artisans',
  'MSME Entrepreneurs',
  'Below Poverty Line',
];

export const APPLICATION_ROUTES = [
  'Online Portal',
  'Bank / Financial Institution',
  'CSC (Common Service Centre)',
  'District / Block Office',
  'State Nodal Agency',
];

// CivicLink scheme catalog: 90 unique schemes listed in the Government of India's DBT Bharat directory.\n// Source: https://dbtbharat.gov.in/central-scheme/list\n// No clone/padding records are used.\nexport const SCHEMES = [
  {
    "id": "SCH-001",
    "name": "Pradhan Mantri Jan-Dhan Yojana (PMJDY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Finance",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-002",
    "name": "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Finance",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Insurance",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-003",
    "name": "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Finance",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Insurance",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-004",
    "name": "Atal Pension Yojana (APY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Finance",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Pension",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-005",
    "name": "Pradhan Mantri MUDRA Yojana (PMMY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Finance",
    "category": "msme",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "MSME Entrepreneurs",
    "sector": "Credit / Loan",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-006",
    "name": "Stand Up India",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Finance",
    "category": "msme",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "MSME Entrepreneurs",
    "sector": "Credit / Loan",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-007",
    "name": "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Finance",
    "category": "msme",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "MSME Entrepreneurs",
    "sector": "Credit / Loan",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-008",
    "name": "Pradhan Mantri Vishwakarma",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Government of India",
    "category": "msme",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "MSME Entrepreneurs",
    "sector": "Credit / Loan",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-009",
    "name": "Prime Minister's Employment Generation Programme (PMEGP)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Government of India",
    "category": "msme",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "MSME Entrepreneurs",
    "sector": "Credit / Loan",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-010",
    "name": "Pradhan Mantri Jan Aushadhi Pariyojana (PMBJP)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Government of India",
    "category": "msme",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-011",
    "name": "Agri Clinics and Agri Business Centres (ACABC)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Farmers",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-012",
    "name": "Agriculture Technology Management Agency (ATMA) - Farmers",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Farmers",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-013",
    "name": "Krishi Unnati Yojana (KUY) - MOVCDNER",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Government of India",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-014",
    "name": "Mission for Aatmanirbharta in Pulses",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Government of India",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-015",
    "name": "Mission for Integrated Development of Horticulture",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Farmers",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-016",
    "name": "Mission Organic Value Chain Development for North East Region",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Government of India",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-017",
    "name": "Modified Interest Subvention Scheme",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Government of India",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-018",
    "name": "National Food Security Mission (NFSM)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-019",
    "name": "National Mission on Edible Oil - Oil Palm",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-020",
    "name": "National Mission on Natural Farming",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-021",
    "name": "NMSA - Rainfed Area Development",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-022",
    "name": "Per Drop More Crop",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-023",
    "name": "PM-KISAN",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Government of India",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-024",
    "name": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Finance",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Farmers",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-025",
    "name": "Pradhan Mantri Kisan Maandhan Yojana (PM-KMY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Farmers",
    "sector": "Agriculture",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-026",
    "name": "RKVY (RAFTAAR)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-027",
    "name": "Sub Mission on Agricultural Mechanization - Central Sector",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Farmers",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-028",
    "name": "Sub Mission on Agricultural Mechanization - Centrally Sponsored",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Farmers",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-029",
    "name": "Sub-Mission on Seeds and Planting Material",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-030",
    "name": "Livestock Health and Disease Control",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Farmers",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-031",
    "name": "Pradhan Mantri Matsya Sampada Yojana (PMMSY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Farmers",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-032",
    "name": "PM-KUSUM",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "category": "agri",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Farmers",
    "sector": "Agriculture",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-033",
    "name": "AICTE Swanath Scholarship Scheme - Degree",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-034",
    "name": "AICTE Swanath Scholarship Scheme - Diploma",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-035",
    "name": "Ishan Uday Special Scholarship Scheme",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-036",
    "name": "National Means-cum-Merit Scholarship Scheme",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-037",
    "name": "National Scholarship for Post-Graduate Studies",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-038",
    "name": "P.G. Scholarship for Professional Courses for SC/ST Candidates",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-039",
    "name": "P.G. Indira Gandhi Scholarship for Single Girl Child",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-040",
    "name": "Pradhan Mantri Uchchatar Shiksha Protsahan - Central Sector Scholarship",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-041",
    "name": "Pradhan Mantri Vidyalaxmi Scheme",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-042",
    "name": "Pragati Scholarship for Girls - Degree",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-043",
    "name": "Pragati Scholarship for Girls - Diploma",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-044",
    "name": "Saksham Scholarship - Degree",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-045",
    "name": "Saksham Scholarship - Diploma",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-046",
    "name": "Prime Minister School for Rising India (PM SHRI)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-047",
    "name": "PM POSHAN",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-048",
    "name": "PM YASASVI - Pre-Matric Scholarship",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-049",
    "name": "PM YASASVI - Post-Matric Scholarship",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-050",
    "name": "PM YASASVI - Top Class School Education",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-051",
    "name": "PM YASASVI - Top Class College Education",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-052",
    "name": "Post-Matric Scholarships for Scheduled Caste Students",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-053",
    "name": "Pre-Matric Scholarship Scheme for Scheduled Castes and Others",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-054",
    "name": "Top Class Education for Scheduled Caste Students",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "SC / ST",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-055",
    "name": "National Fellowship for Scheduled Caste Students (NFSC)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-056",
    "name": "National Overseas Scholarship (NOS)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-057",
    "name": "PM DAKSH Scheme",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "OBC",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-058",
    "name": "Scheme for Economic Empowerment of DNTs (SEED)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "OBC",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-059",
    "name": "SHRESHTA",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-060",
    "name": "SHREYAS - Dr. Ambedkar Interest Subsidy",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-061",
    "name": "SHREYAS - National Fellowship for OBC Students",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-062",
    "name": "VISVAS",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-063",
    "name": "Atal Vayo Abhyuday Yojana (AVYAY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-064",
    "name": "NAMASTE",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-065",
    "name": "National Action Plan for Drug Demand Reduction (NAPDDR)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-066",
    "name": "ADIP - Assistance to Disabled Persons for Purchase/Fitting of Aids and Appliances",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-067",
    "name": "Deen Dayal Disabled Rehabilitation Scheme",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-068",
    "name": "National Fellowship for Students with Disabilities",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Social Justice and Empowerment",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-069",
    "name": "Post-Matric Scholarship for Persons with Disabilities",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Education",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-070",
    "name": "DAY-NRLM",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "msme",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "MSME Entrepreneurs",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-071",
    "name": "Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "msme",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "MSME Entrepreneurs",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-072",
    "name": "Indira Gandhi National Disability Pension Scheme (IGNDPS)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Pension",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-073",
    "name": "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Pension",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-074",
    "name": "Indira Gandhi National Widow Pension Scheme (IGNWPS)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Pension",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-075",
    "name": "Mahatma Gandhi NREGA",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-076",
    "name": "National Family Benefit Scheme",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-077",
    "name": "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Housing",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-078",
    "name": "Viksit Bharat-Guarantee for Rozgar and Ajeevika Mission (Gramin)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Employment",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-079",
    "name": "Pradhan Mantri Shram Yogi Maandhan (PM-SYM)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "social",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Pension",
    "route": "Bank / Financial Institution",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-080",
    "name": "Prime Minister Internship Scheme",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Rural Development",
    "category": "edu",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Students",
    "sector": "Education",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-081",
    "name": "AB-PMJAY",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Health and Family Welfare",
    "category": "health",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Health",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-082",
    "name": "Janani Shishu Suraksha Karyakram (JSSK)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Health and Family Welfare",
    "category": "health",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Health",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-083",
    "name": "Janani Suraksha Yojana (JSY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Health and Family Welfare",
    "category": "health",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Health",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-084",
    "name": "NIKSHAY - TB Nutritional Support",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Health and Family Welfare",
    "category": "health",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Health",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-085",
    "name": "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Health and Family Welfare",
    "category": "health",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Women",
    "sector": "Health",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-086",
    "name": "Mission Vatsalya",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Women and Child Development",
    "category": "health",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Women",
    "sector": "Health",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-087",
    "name": "PALNA",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Women and Child Development",
    "category": "health",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Women",
    "sector": "Health",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-088",
    "name": "Shakti Sadan",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Women and Child Development",
    "category": "health",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "Women",
    "sector": "Health",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-089",
    "name": "PM-SURYA GHAR MUFT BIJLI YOJANA",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of New and Renewable Energy",
    "category": "health",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Subsidy",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  },
  {
    "id": "SCH-090",
    "name": "Pradhan Mantri Ujjwala Yojana",
    "tag": "Government scheme listed on DBT Bharat",
    "ministry": "Ministry of Petroleum and Natural Gas",
    "category": "health",
    "desc": "Listed in the Government of India's Direct Benefit Transfer (DBT) Bharat scheme directory. Check current official guidelines for eligibility, benefits and application conditions.",
    "loan": "See official guidelines",
    "rate": "See official guidelines",
    "beneficiary": "General Citizen",
    "sector": "Subsidy",
    "route": "Online Portal",
    "verified": true,
    "verificationSource": "DBT Bharat",
    "sourceUrl": "https://dbtbharat.gov.in/central-scheme/list",
    "lastVerified": "2026-09-24"
  }
];\n\nexport const PARTNERS = [
  { id: 'p1', name: 'Bank of India \u2013 Connaught Place Branch', type: 'Bank / MUDRA Nodal', address: 'Parliament Street, New Delhi, 110001', distance: '1.2 km', phone: '011-2334-5678', state: 'Delhi', district: 'New Delhi' },
  { id: 'p2', name: 'CSC Digital Seva Kendra \u2013 Karol Bagh', type: 'Common Service Centre', address: 'Karol Bagh Main Market, New Delhi', distance: '3.4 km', phone: '011-2578-1122', state: 'Delhi', district: 'New Delhi' },
  { id: 'p3', name: 'NABARD Regional Office', type: 'NABARD / Agri Credit', address: 'Mumbai Central, Maharashtra', distance: '5.1 km', phone: '022-2653-9876', state: 'Maharashtra', district: 'Mumbai' },
  { id: 'p4', name: 'District Industries Centre (DIC) Pune', type: 'State Nodal Agency', address: 'Shivaji Nagar, Pune, 411005', distance: '2.8 km', phone: '020-2551-4400', state: 'Maharashtra', district: 'Pune' },
  { id: 'p5', name: 'SIDBI Branch \u2013 Bengaluru', type: 'SIDBI / MSME', address: 'MG Road, Bengaluru, 560001', distance: '4.6 km', phone: '080-2558-1200', state: 'Karnataka', district: 'Bengaluru Urban' },
  { id: 'p6', name: 'Pashusakhi Livestock Kendra', type: 'NLM Facilitation Centre', address: 'Jaipur, Rajasthan', distance: '6.2 km', phone: '0141-256-7788', state: 'Rajasthan', district: 'Jaipur' },
];

export const CHAT_QUESTIONS = [
  { key: 'name', q: 'Namaste! I am the CivicLink Assistant. May I know your name?', type: 'text', placeholder: 'Your full name' },
  { key: 'age', q: 'Thank you. What is your age in years?', type: 'number', placeholder: 'e.g. 28' },
  { key: 'gender', q: 'Please share your gender.', type: 'choice', options: ['Female', 'Male', 'Other'] },
  { key: 'category', q: 'Which social category do you belong to?', type: 'choice', options: ['General', 'OBC', 'SC', 'ST', 'Minority'] },
  { key: 'income', q: 'What is your approximate annual family income (\u20B9)?', type: 'choice', options: ['Below 2.5 Lakh', '2.5 \u2013 5 Lakh', '5 \u2013 8 Lakh', 'Above 8 Lakh'] },
  { key: 'occupation', q: 'What best describes your occupation?', type: 'choice', options: ['Farmer', 'Artisan / Craftsperson', 'Small Business / MSME', 'Student', 'Salaried', 'Homemaker', 'Unemployed'] },
  { key: 'state', q: 'Which state do you live in?', type: 'choice', options: ['Delhi', 'Maharashtra', 'Uttar Pradesh', 'Karnataka', 'Tamil Nadu', 'Bihar', 'Rajasthan', 'Gujarat', 'Other'] },
  { key: 'need', q: 'What kind of support are you looking for?', type: 'choice', options: ['Business Loan', 'Education / Scholarship', 'Health / Insurance', 'Pension / Social Security', 'Housing', 'Agriculture Support'] },
];

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'mr', label: 'मराठी' },
  { code: 'gu', label: 'ગુજરાતી' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
  { code: 'ml', label: 'മലയാളം' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ' },
  { code: 'or', label: 'ଓଡ଼ିଆ' },
  { code: 'as', label: 'অসমীয়া' },
];

// Deterministic rule-based scheme matching
export function matchSchemes(profile) {
  const results = SCHEMES.map((s) => {
    let score = 40;
    const reasons = [];
    const unmet = [];

    // occupation-based
    if (profile.occupation === 'Farmer' && s.category === 'agri') { score += 25; reasons.push('You reported farming as your occupation'); }
    if (profile.occupation === 'Artisan / Craftsperson' && s.category === 'artisan') { score += 25; reasons.push('Traditional artisan trades are covered'); }
    if (profile.occupation === 'Small Business / MSME' && s.category === 'msme') { score += 25; reasons.push('MSME entrepreneurs are the target group'); }
    if (profile.occupation === 'Student' && s.category === 'edu') { score += 25; reasons.push('Students are eligible for this scholarship'); }

    // need-based
    if (profile.need === 'Business Loan' && s.category === 'msme') { score += 15; reasons.push('Matches your requirement for business credit'); }
    if (profile.need === 'Education / Scholarship' && s.category === 'edu') { score += 15; reasons.push('Matches your scholarship requirement'); }
    if (profile.need === 'Health / Insurance' && s.category === 'health') { score += 15; reasons.push('Provides health / insurance coverage'); }
    if (profile.need === 'Pension / Social Security' && s.category === 'social') { score += 15; reasons.push('Provides social security & pension benefits'); }
    if (profile.need === 'Housing' && s.sector === 'Housing') { score += 15; reasons.push('Provides housing assistance'); }
    if (profile.need === 'Agriculture Support' && s.category === 'agri') { score += 15; reasons.push('Supports agriculture and rural development'); }

    // gender
    if (profile.gender === 'Female' && (s.beneficiary === 'Women' || s.name.includes('Women'))) { score += 10; reasons.push('Prioritised for women beneficiaries'); }

    // income
    if (profile.income && profile.income.startsWith('Below') && s.beneficiary === 'Below Poverty Line') { score += 10; reasons.push('Income bracket aligns with beneficiary criteria'); }

    // age
    const age = parseInt(profile.age || '0', 10);
    if (age >= 18 && age <= 70 && s.sector === 'Insurance') { score += 5; reasons.push('Age falls within eligibility window'); }
    if (age >= 60 && s.category === 'social' && s.name.includes('Pension')) { score += 8; reasons.push('Senior citizen eligible for pension benefits'); }

    if (reasons.length === 0) unmet.push('Profile does not directly indicate a primary match');

    return { scheme: s, score: Math.min(score, 98), reasons, unmet };
  });

  results.sort((a, b) => b.score - a.score);
  return results.slice(0, 12);
}
